// AUTO-GENERATED by opticc (syntax->hir->typeck->cgir->opt->codegen)
use optic_runtime::Cursor;

#[derive(Debug, Clone, Copy, Default)]
pub struct Transform {
    pub position: (f32, f32),
}

#[derive(Debug)]
pub struct Entities {
    pub transforms: Vec<Transform>,
}

// optic(fused): [TransformView, PositionField]
pub fn run_example(entities: &mut Entities) {
    let n = entities.transforms.len();
    for id_0 in 0..n {
        let cursor_0 = Cursor::new(entities, id_0);
        let mut _c0 = cursor_0.arena.transforms[cursor_0.id];
        let _c1 = _c0.position;
        let _updated = (_c1.0 + 0.1, _c1.1 + 0.1);
        _c0.position = _updated;
        cursor_0.arena.transforms[cursor_0.id] = _c0;
    }
}

fn main() {
    let mut world = Entities { transforms: vec![Transform { position: (0.0, 0.0) }, Transform { position: (1.0, 1.0) }, Transform { position: (2.0, 2.0) }] };
    println!("before: {:?}", world);
    run_example(&mut world);
    println!("after:  {:?}", world);
}
