// AUTO-GENERATED by opticc (syntax->hir->typeck->cgir->opt->codegen)
use optic_runtime::Cursor;

#[derive(Debug)]
pub struct Entities {
    pub healths: Vec<f32>,
    pub positions: Vec<(f32, f32)>,
}

// optic(record): health_decay
pub fn run_example(entities: &mut Entities) {
    let n = entities.healths.len();
    for id_0 in 0..n {
        let cursor_0 = Cursor::new(entities, id_0);
        let _healths = cursor_0.arena.healths[cursor_0.id];
        let _new = _healths - 10.0;
        cursor_0.arena.healths[cursor_0.id] = _new;
    }
}

fn main() {
    let mut world = Entities { healths: vec![100.0, 80.0, 50.0], positions: vec![(0.0,0.0), (1.0,1.0), (2.0,2.0)] };
    println!("before: {:?}", world);
    run_example(&mut world);
    println!("after:  {:?}", world);
}
