// AUTO-GENERATED by opticc (syntax->hir->typeck->cgir->opt->codegen)
use optic_runtime::Cursor;

#[derive(Debug)]
pub struct Entities {
    pub healths: Vec<f32>,
}

// optic(fused): [HealthView, DoubleView]
pub fn run_example(entities: &mut Entities) {
    let n = entities.healths.len();
    for id_0 in 0..n {
        let cursor_0 = Cursor::new(entities, id_0);
        let _c0 = cursor_0.arena.healths[cursor_0.id];
        let _c1 = _c0 * 2.0;
        let _updated = _c1 - 10.0;
        let _p1 = _updated / 2.0;
        cursor_0.arena.healths[cursor_0.id] = _p1;
    }
}

fn main() {
    let mut world = Entities { healths: vec![100.0, 80.0, 50.0] };
    println!("before: {:?}", world);
    run_example(&mut world);
    println!("after:  {:?}", world);
}
