// AUTO-GENERATED by opticc (syntax->hir->typeck->cgir->opt->codegen)
use optic_runtime::Cursor;

#[derive(Debug)]
pub struct Entities {
    pub healths: Vec<f32>,
    pub positions: Vec<(f32, f32)>,
}

// optic(fused): [HealthView, PositionView]
pub fn run_example(entities: &mut Entities) {
    let n = entities.healths.len();
    assert_eq!(n, entities.positions.len());
    for id_0 in 0..n {
        let cursor_0 = Cursor::new(entities, id_0);
        let _healths = cursor_0.arena.healths[cursor_0.id];
        let _positions = cursor_0.arena.positions[cursor_0.id];
        let (_healths_new, _positions_new) = (_healths - 1.0, (_positions.0 + 0.1, _positions.1));
        cursor_0.arena.healths[cursor_0.id] = _healths_new;
        cursor_0.arena.positions[cursor_0.id] = _positions_new;
    }
}

fn main() {
    let mut world = Entities { healths: vec![100.0, 80.0, 50.0], positions: vec![(0.0,0.0), (1.0,1.0), (2.0,2.0)] };
    println!("before: {:?}", world);
    run_example(&mut world);
    println!("after:  {:?}", world);
}
