// AUTO-GENERATED by opticc (syntax->hir->typeck->cgir->opt->codegen)
use optic_runtime::Cursor;

#[derive(Debug, Clone, Copy, Default)]
pub struct Meta {
    pub tag: f32,
}

#[derive(Debug, Clone, Copy, Default)]
pub struct Transform {
    pub meta: Meta,
    pub position: (f32, f32),
}

#[derive(Debug)]
pub struct Entities {
    pub transforms: Vec<Transform>,
}

// optic(fused): [TransformView, MetaField, TagField]
pub fn run_example(entities: &mut Entities) {
    let n = entities.transforms.len();
    for id_0 in 0..n {
        let cursor_0 = Cursor::new(entities, id_0);
        let mut _c0 = cursor_0.arena.transforms[cursor_0.id];
        let mut _c1 = _c0.meta;
        let _c2 = _c1.tag;
        let _updated = _c2 + 0.1;
        _c1.tag = _updated;
        _c0.meta = _c1;
        cursor_0.arena.transforms[cursor_0.id] = _c0;
    }
}

fn main() {
    let mut world = Entities { transforms: vec![Transform { meta: Meta { ..Default::default() }, position: (0.0, 0.0) }, Transform { meta: Meta { ..Default::default() }, position: (1.0, 1.0) }, Transform { meta: Meta { ..Default::default() }, position: (2.0, 2.0) }] };
    println!("before: {:?}", world);
    run_example(&mut world);
    println!("after:  {:?}", world);
}
