// AUTO-GENERATED by opticc (syntax->hir->typeck->cgir->opt->codegen)
use optic_runtime::Cursor;

#[derive(Debug)]
pub struct Entities {
    pub healths: Vec<f32>,
}

// optic(traversal): AllHealths
// simd-eligible
pub fn run_example(entities: &mut Entities) {
    let n = entities.healths.len();
    // chunked vector-packed (portable SIMD-friendly nest width 4; remainder safe)
    let mut id_base = 0;
    while id_base < n {
        let w = std::cmp::min(4usize, n - id_base);
        for _l in 0..w {
            let id_0 = id_base + _l;
            let cursor_0 = Cursor::new(entities, id_0);
            let _set_lit = 42.0;
            let _set_out = _set_lit;
            cursor_0.arena.healths[cursor_0.id] = _set_out;
        }
        id_base += w;
    }
}

fn main() {
    let mut world = Entities { healths: vec![100.0, 80.0, 50.0] };
    println!("before: {:?}", world);
    run_example(&mut world);
    println!("after:  {:?}", world);
}
