#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import hashlib
import json
import sys

ROOT = Path(__file__).resolve().parents[1]
REGISTRY_PATH = ROOT / 'agent-system' / 'registry.json'
GENERATED_DIR = ROOT / 'agent-system' / 'generated'
INDEX_PATH = GENERATED_DIR / 'context-index.md'
MATRIX_PATH = GENERATED_DIR / 'tool-matrix.md'

SHARED_MEMORY_MAX_LINES = 200
AGENT_MEMORY_MAX_LINES = 120


def read(path: Path) -> str:
    return path.read_text(encoding='utf-8')


def sha8(path: Path) -> str:
    h = hashlib.sha256(path.read_bytes()).hexdigest()
    return h[:8]


def line_count(path: Path) -> int:
    return read(path).count('\n') + 1


def require(path: Path, errors: list[str]) -> bool:
    if not path.exists():
        errors.append(f'missing required file: {path.relative_to(ROOT)}')
        return False
    return True


def generate_context_index(registry: dict) -> str:
    lines = []
    lines.append('# Generated Context Index\n')
    lines.append('This file is generated by `python tools/agent_sync.py`. Do not hand-edit it.\n')
    lines.append('## Canonical roots\n')
    lines.append('- `AGENTS.md` is the canonical instruction hub.\n')
    lines.append('- `agent-system/memory/SHARED_MEMORY.md` is the canonical shared repository memory.\n')
    lines.append('- `manifest.json` defines assembly order.\n')
    lines.append('- `assembled.md` is generated output.\n')
    lines.append('\n## Agent registry\n')
    lines.append('| Agent | Role | Memory | Claude file | Kilo file | Writes | Delegates to |\n')
    lines.append('|---|---|---|---|---|---|---|\n')
    for agent in registry['agents']:
        writes = ', '.join(agent.get('writes', []))
        delegates = ', '.join(agent.get('delegatesTo', [])) or '—'
        lines.append(f"| `{agent['name']}` | {agent['role']} | `{agent['memory']}` | `{agent['claude']}` | `{agent['kilo']}` | {writes} | {delegates} |\n")
    lines.append('\n## File fingerprints\n')
    lines.append('| File | Hash | Lines |\n')
    lines.append('|---|---:|---:|\n')
    tracked = [ROOT / 'AGENTS.md', ROOT / 'CLAUDE.md', ROOT / 'GEMINI.md', ROOT / 'CONTEXT.md']
    tracked += sorted((ROOT / '.claude' / 'agents').glob('*.md'))
    tracked += sorted((ROOT / '.kilo' / 'agents').glob('*.md'))
    tracked += [ROOT / 'agent-system' / 'README.md', ROOT / 'agent-system' / 'OPERATING_MODEL.md', ROOT / 'agent-system' / 'MEMORY_MODEL.md', ROOT / 'agent-system' / 'TASK_PACKET_TEMPLATE.md', ROOT / 'agent-system' / 'TOOL_COMPATIBILITY.md', ROOT / 'agent-system' / 'RESEARCH_BASIS.md']
    tracked += [ROOT / 'agent-system' / 'memory' / 'SHARED_MEMORY.md', ROOT / 'agent-system' / 'memory' / 'FAILED_PATCH_RECORDS.md']
    tracked += sorted((ROOT / 'agent-system' / 'memory' / 'agents').glob('*.md'))
    for path in tracked:
        rel = path.relative_to(ROOT)
        lines.append(f'| `{rel}` | `{sha8(path)}` | {line_count(path)} |\n')
    return ''.join(lines)


def generate_tool_matrix() -> str:
    return """# Generated Tool Matrix\n\nThis file is generated by `python tools/agent_sync.py`. Do not hand-edit it.\n\n| Tool | Canonical entry file(s) | Notes |\n|---|---|---|\n| Claude Code | `CLAUDE.md`, `.claude/agents/*.md`, `AGENTS.md` | project subagents plus canonical hub |\n| OpenAI Codex | `AGENTS.md` | use task packets for parallel, well-scoped work |\n| Gemini CLI | `GEMINI.md`, `AGENTS.md` | concise wrapper plus canonical hub |\n| GitHub Copilot / VS Code Copilot | `.github/copilot-instructions.md`, `.github/instructions/*.instructions.md`, `AGENTS.md` | path-specific narrowing for markdown and assembly work |\n| Kilo CLI / extension | `AGENTS.md`, `CONTEXT.md`, `.kilo/agents/*.md` | wrapper files plus project-local custom agents |\n"""


def main() -> int:
    errors: list[str] = []
    warnings: list[str] = []

    registry = json.loads(read(REGISTRY_PATH))

    required = [
        ROOT / 'AGENTS.md',
        ROOT / 'CLAUDE.md',
        ROOT / 'GEMINI.md',
        ROOT / 'CONTEXT.md',
        ROOT / '.github' / 'copilot-instructions.md',
        ROOT / 'agent-system' / 'README.md',
        ROOT / 'agent-system' / 'OPERATING_MODEL.md',
        ROOT / 'agent-system' / 'MEMORY_MODEL.md',
        ROOT / 'agent-system' / 'TASK_PACKET_TEMPLATE.md',
        ROOT / 'agent-system' / 'TOOL_COMPATIBILITY.md',
        ROOT / 'agent-system' / 'RESEARCH_BASIS.md',
        ROOT / 'agent-system' / 'memory' / 'SHARED_MEMORY.md',
        ROOT / 'agent-system' / 'memory' / 'FAILED_PATCH_RECORDS.md',
        ROOT / 'assemble_book.py',
        ROOT / 'manifest.json',
    ]
    for path in required:
        require(path, errors)

    for agent in registry['agents']:
        for key in ['memory', 'claude', 'kilo']:
            require(ROOT / agent[key], errors)

    shared = ROOT / 'agent-system' / 'memory' / 'SHARED_MEMORY.md'
    if shared.exists() and line_count(shared) > SHARED_MEMORY_MAX_LINES:
        warnings.append(f'shared memory exceeds soft limit ({line_count(shared)} lines > {SHARED_MEMORY_MAX_LINES})')

    agent_dir = ROOT / 'agent-system' / 'memory' / 'agents'
    if agent_dir.exists():
        for path in sorted(agent_dir.glob('*.md')):
            if line_count(path) > AGENT_MEMORY_MAX_LINES:
                warnings.append(f'{path.relative_to(ROOT)} exceeds soft limit ({line_count(path)} lines > {AGENT_MEMORY_MAX_LINES})')

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    INDEX_PATH.write_text(generate_context_index(registry), encoding='utf-8')
    MATRIX_PATH.write_text(generate_tool_matrix(), encoding='utf-8')

    if warnings:
        sys.stderr.write('Warnings:\n')
        for w in warnings:
            sys.stderr.write(f'  - {w}\n')

    if errors:
        sys.stderr.write('Errors:\n')
        for e in errors:
            sys.stderr.write(f'  - {e}\n')
        return 1

    print('agent system OK')
    print(f'wrote {INDEX_PATH.relative_to(ROOT)}')
    print(f'wrote {MATRIX_PATH.relative_to(ROOT)}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
