//! optic-codegen-rust — emit exact ch. 11 loop shapes from (post-fusion) CGIR (M5).

use optic_cgir::{format_hir_expr, CgirGraph, CgirNode, NodeId};
use optic_hir::HirExpr;

enum QueryMode {
    MapDecay { root: NodeId },
    MapProduct { root: NodeId },
    Get { root: NodeId },
    Set { root: NodeId },
}

const RUST_KEYWORDS: &[&str] = &[
    "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum", "extern",
    "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub",
    "ref", "return", "self", "Self", "static", "struct", "super", "trait", "true", "type",
    "unsafe", "use", "where", "while",
];

/// Reject user-derived names that would emit invalid Rust identifiers.
fn is_valid_rust_ident(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !first.is_ascii_alphabetic() && first != '_' {
        return false;
    }
    if !chars.all(|c| c.is_ascii_alphanumeric() || c == '_') {
        return false;
    }
    !RUST_KEYWORDS.contains(&name)
}

fn validate_user_ident(name: &str, context: &str) -> Result<(), String> {
    if is_valid_rust_ident(name) {
        Ok(())
    } else if RUST_KEYWORDS.contains(&name) {
        Err(format!("reserved Rust keyword for {context}: {name:?}"))
    } else {
        Err(format!("invalid Rust identifier for {context}: {name:?}"))
    }
}

pub fn emit(graph: &CgirGraph, _runtime: &str) -> Result<String, String> {
    let mut out = String::with_capacity(1024);
    out.push_str("// AUTO-GENERATED by opticc (syntax->hir->typeck->cgir->opt->codegen)\n");
    out.push_str("use optic_runtime::Cursor;\n\n");

    let query_mode = detect_query_mode(graph);
    let leaf_nodes: Vec<_> = graph
        .nodes
        .iter()
        .filter_map(|n| {
            if let CgirNode::OpticLeaf { name, summary, .. } = n {
                Some((name.clone(), summary))
            } else {
                None
            }
        })
        .collect();

    let mut all_regions: Vec<String> = vec![];
    let mut leaf_names: Vec<String> = vec![];
    let mut seen = std::collections::HashSet::new();
    for (nm, sum) in &leaf_nodes {
        validate_user_ident(nm, "optic name")?;
        leaf_names.push(nm.clone());
        for r in sum
            .get_reads
            .iter()
            .chain(&sum.put_writes)
            .chain(&sum.put_reads)
        {
            if seen.insert(r.clone()) {
                all_regions.push(r.clone());
            }
        }
    }

    let est = 1024 + leaf_names.len() * 128 + all_regions.len() * 64;
    out.reserve(est.max(4096));

    out.push_str("#[derive(Debug)]\npub struct Entities {\n");
    for reg in &all_regions {
        let field = region_field(reg);
        validate_user_ident(&field, "region field")?;
        out.push_str(&format!("    pub {}: {},\n", field, region_ty(reg)));
    }
    if all_regions.is_empty() {
        out.push_str("    pub healths: Vec<f32>,\n");
    }
    out.push_str("}\n\n");

    match &query_mode {
        QueryMode::Get { root } => {
            let optic_name = query_optic_name(graph, *root);
            let field = primary_field_for_optic(graph, &optic_name);
            out.push_str("pub fn run_example(entities: &mut Entities) {\n");
            out.push_str(&format!("    let n = entities.{}.len();\n", field));
            out.push_str("    for id_0 in 0..n {\n");
            out.push_str("        let cursor_0 = Cursor::new(entities, id_0);\n");
            out.push_str(&format!(
                "        let _v = cursor_0.arena.{}[cursor_0.id];\n",
                field
            ));
            out.push_str("        println!(\"get: {}\", _v);\n");
            out.push_str("    }\n}\n\n");
        }
        QueryMode::Set { root } => {
            let CgirNode::QuerySet {
                optic_name,
                value_repr,
                ..
            } = &graph.nodes[*root as usize]
            else {
                panic!("invalid set root");
            };
            let field = primary_field_for_optic(graph, optic_name);
            let lit = f32_literal(value_repr);
            out.push_str("pub fn run_example(entities: &mut Entities) {\n");
            out.push_str(&format!("    let n = entities.{}.len();\n", field));
            out.push_str("    for id_0 in 0..n {\n");
            out.push_str("        let cursor_0 = Cursor::new(entities, id_0);\n");
            out.push_str(&format!(
                "        cursor_0.arena.{}[cursor_0.id] = {lit};\n",
                field
            ));
            out.push_str("    }\n}\n\n");
        }
        QueryMode::MapProduct { root } => {
            let CgirNode::QueryMap {
                optic_name,
                map_body,
                map_param,
                ..
            } = &graph.nodes[*root as usize]
            else {
                return Err("invalid map root".into());
            };
            let product_regions = product_regions_ordered(graph, optic_name);
            let regions = if product_regions.is_empty() {
                all_regions.clone()
            } else {
                product_regions
            };
            let comment_names = if leaf_names.is_empty() {
                "unknown".to_string()
            } else {
                leaf_names.join(", ")
            };
            out.push_str(&format!("// optic(fused): [{}]\n", comment_names));
            let n_field = regions
                .first()
                .map(|r| region_field(r))
                .unwrap_or_else(|| "healths".into());
            out.push_str("pub fn run_example(entities: &mut Entities) {\n");
            out.push_str(&format!("    let n = entities.{n_field}.len();\n"));
            for reg in regions.iter().skip(1) {
                let f = region_field(reg);
                out.push_str(&format!("    assert_eq!(n, entities.{f}.len());\n"));
            }
            out.push_str("    for id_0 in 0..n {\n");
            out.push_str("        let cursor_0 = Cursor::new(entities, id_0);\n");
            for reg in &regions {
                let f = region_field(reg);
                let bind = region_bind(reg);
                out.push_str(&format!(
                    "        let {bind} = cursor_0.arena.{f}[cursor_0.id];\n"
                ));
            }
            let binds: Vec<String> = regions.iter().map(|r| region_bind(r)).collect();
            for p in map_param
                .split(',')
                .map(str::trim)
                .filter(|s| !s.is_empty())
            {
                validate_user_ident(p, "map parameter")?;
            }
            let body_rust = emit_map_body_product(map_body.as_ref(), map_param, &binds)?;
            emit_product_stores(&mut out, &regions, &body_rust, map_body.as_ref())?;
            out.push_str("    }\n}\n\n");
        }
        QueryMode::MapDecay { root } => {
            let CgirNode::QueryMap {
                map_body,
                map_param,
                ..
            } = &graph.nodes[*root as usize]
            else {
                return Err("invalid map root".into());
            };
            let field = all_regions
                .first()
                .map(|r| region_field(r))
                .unwrap_or_else(|| "healths".into());
            let bind = region_bind(all_regions.first().map(|s| s.as_str()).unwrap_or("healths"));
            out.push_str("pub fn run_example(entities: &mut Entities) {\n");
            out.push_str(&format!("    let n = entities.{field}.len();\n"));
            out.push_str("    for id_0 in 0..n {\n");
            out.push_str("        let cursor_0 = Cursor::new(entities, id_0);\n");
            out.push_str(&format!(
                "        let {bind} = cursor_0.arena.{field}[cursor_0.id];\n"
            ));
            validate_user_ident(map_param, "map parameter")?;
            let body_rust = emit_map_body(map_body.as_ref(), map_param, &bind)?;
            out.push_str(&format!(
                "        let _new = {body_rust};\n        cursor_0.arena.{field}[cursor_0.id] = _new;\n"
            ));
            out.push_str("    }\n}\n\n");
        }
    }

    out.push_str("fn main() {\n    let mut world = Entities { ");
    let mut inits = vec!["healths: vec![100.0, 80.0, 50.0]".to_string()];
    if all_regions.iter().any(|r| r.contains("pos")) {
        inits.push("positions: vec![(0.0,0.0), (1.0,1.0), (2.0,2.0)]".into());
    }
    out.push_str(&inits.join(", "));
    out.push_str(" };\n");
    out.push_str("    println!(\"before: {:?}\", world);\n");
    out.push_str("    run_example(&mut world);\n");
    out.push_str("    println!(\"after:  {:?}\", world);\n");
    out.push_str("}\n");
    Ok(out)
}

fn emit_product_stores(
    out: &mut String,
    regions: &[String],
    body_rust: &str,
    map_body: &HirExpr,
) -> Result<(), String> {
    let new_names: Vec<String> = regions
        .iter()
        .map(|r| format!("{}_new", region_bind(r)))
        .collect();
    if matches!(map_body, HirExpr::Tuple(elems, _) if elems.len() == regions.len()) {
        out.push_str("        let (");
        out.push_str(&new_names.join(", "));
        out.push_str(") = ");
        out.push_str(body_rust);
        out.push_str(";\n");
        for (reg, new_name) in regions.iter().zip(&new_names) {
            let f = region_field(reg);
            out.push_str(&format!(
                "        cursor_0.arena.{f}[cursor_0.id] = {new_name};\n"
            ));
        }
        return Ok(());
    }
    if regions.len() > 1 {
        return Err(format!(
            "product map tuple arity mismatch: {} regions, body {:?}",
            regions.len(),
            map_body
        ));
    } else {
        let field = regions
            .first()
            .map(|r| region_field(r))
            .unwrap_or_else(|| "healths".into());
        out.push_str(&format!("        let _new = {body_rust};\n"));
        out.push_str(&format!(
            "        cursor_0.arena.{field}[cursor_0.id] = _new;\n"
        ));
    }
    Ok(())
}

fn query_optic_name(graph: &CgirGraph, root: NodeId) -> String {
    match graph.nodes.get(root as usize) {
        Some(CgirNode::QueryGet { optic_name, .. })
        | Some(CgirNode::QuerySet { optic_name, .. })
        | Some(CgirNode::QueryMap { optic_name, .. }) => optic_name.clone(),
        _ => "unknown".into(),
    }
}

fn product_regions_ordered(graph: &CgirGraph, optic_name: &str) -> Vec<String> {
    let Some(&nid) = graph.resolved_optics.get(optic_name) else {
        return vec![];
    };
    collect_regions_from_node(graph, nid)
}

fn collect_regions_from_node(graph: &CgirGraph, nid: NodeId) -> Vec<String> {
    match graph.nodes.get(nid as usize) {
        Some(CgirNode::Product { lhs, rhs, .. }) => {
            let mut out = collect_regions_from_node(graph, *lhs);
            out.extend(collect_regions_from_node(graph, *rhs));
            out
        }
        Some(CgirNode::Compose { lhs, rhs, .. }) => {
            let mut out = collect_regions_from_node(graph, *lhs);
            out.extend(collect_regions_from_node(graph, *rhs));
            out
        }
        Some(CgirNode::OpticLeaf { summary, .. }) => summary.get_reads.clone(),
        _ => vec![],
    }
}

fn emit_map_body(body: &HirExpr, map_param: &str, load_bind: &str) -> Result<String, String> {
    emit_hir_expr_rust(body, map_param, load_bind, None)
}

fn emit_map_body_product(
    body: &HirExpr,
    map_param: &str,
    binds: &[String],
) -> Result<String, String> {
    emit_hir_expr_rust(
        body,
        map_param,
        binds.first().map(|s| s.as_str()).unwrap_or("_v"),
        Some(binds),
    )
}

fn emit_hir_expr_rust(
    e: &HirExpr,
    map_param: &str,
    load_bind: &str,
    product_binds: Option<&[String]>,
) -> Result<String, String> {
    match e {
        HirExpr::LitInt(n, _) => Ok(format!("{n}.0")),
        HirExpr::LitFloat(f, _) => Ok(if f.fract() == 0.0 {
            format!("{f:.1}")
        } else {
            f.to_string()
        }),
        HirExpr::Var(v, _) => {
            validate_user_ident(v, "map variable")?;
            if let Some(binds) = product_binds {
                let params: Vec<&str> = map_param.split(',').map(str::trim).collect();
                if let Some(i) = params.iter().position(|p| *p == v) {
                    return Ok(binds.get(i).cloned().unwrap_or_else(|| v.clone()));
                }
            }
            Ok(if v == map_param {
                load_bind.to_string()
            } else {
                v.clone()
            })
        }
        HirExpr::Paren(inner, _) => {
            let inner_rust = emit_hir_expr_rust(inner, map_param, load_bind, product_binds)?;
            Ok(format!("({inner_rust})"))
        }
        HirExpr::Bin {
            op, left, right, ..
        } => {
            let op_s = match op {
                optic_syntax::BinOp::Add => "+",
                optic_syntax::BinOp::Sub => "-",
                optic_syntax::BinOp::Mul => "*",
                optic_syntax::BinOp::Div => "/",
                other => {
                    return Err(format!(
                        "unsupported binary operator in map body: {other:?}"
                    ));
                }
            };
            Ok(format!(
                "({} {} {})",
                emit_hir_expr_rust(left, map_param, load_bind, product_binds)?,
                op_s,
                emit_hir_expr_rust(right, map_param, load_bind, product_binds)?
            ))
        }
        HirExpr::Tuple(elems, _) => {
            let parts: Vec<_> = elems
                .iter()
                .map(|el| emit_hir_expr_rust(el, map_param, load_bind, product_binds))
                .collect::<Result<_, _>>()?;
            Ok(format!("({})", parts.join(", ")))
        }
        HirExpr::TupleProj { base, index, .. } => Ok(format!(
            "{}.{}",
            emit_hir_expr_rust(base, map_param, load_bind, product_binds)?,
            index
        )),
        HirExpr::Unsupported { reason, .. } => Err(format!("unsupported map body: {reason}")),
        _ => Ok(format_hir_expr(e)),
    }
}

fn region_field(reg: &str) -> String {
    if reg.contains("health") {
        "healths".into()
    } else if reg.contains("pos") {
        "positions".into()
    } else {
        reg.to_string()
    }
}

fn region_bind(reg: &str) -> String {
    if reg.contains("health") {
        "_h".into()
    } else if reg.contains("pos") {
        "_p".into()
    } else {
        format!("_{reg}")
    }
}

fn region_ty(reg: &str) -> &'static str {
    if reg.contains("pos") {
        "Vec<(f32, f32)>"
    } else {
        "Vec<f32>"
    }
}

fn primary_field_for_optic(graph: &CgirGraph, name: &str) -> String {
    graph
        .nodes
        .iter()
        .find_map(|n| {
            if let CgirNode::OpticLeaf {
                name: leaf_name,
                summary,
                ..
            } = n
            {
                if leaf_name == name {
                    return summary.get_reads.first().map(|r| region_field(r));
                }
            }
            None
        })
        .unwrap_or_else(|| "healths".into())
}

fn f32_literal(value: &str) -> String {
    if value.contains('.') {
        value.to_string()
    } else {
        format!("{value}.0")
    }
}

fn detect_query_mode(graph: &CgirGraph) -> QueryMode {
    let has_product = graph
        .nodes
        .iter()
        .any(|n| matches!(n, CgirNode::Product { .. } | CgirNode::FusedLoop { .. }));

    for &root in &graph.roots {
        if let Some(node) = graph.nodes.get(root as usize) {
            return match node {
                CgirNode::QueryGet { .. } => QueryMode::Get { root },
                CgirNode::QuerySet { .. } => QueryMode::Set { root },
                CgirNode::QueryMap { .. } => {
                    if has_product {
                        QueryMode::MapProduct { root }
                    } else {
                        QueryMode::MapDecay { root }
                    }
                }
                _ => continue,
            };
        }
    }
    QueryMode::MapDecay { root: 0 }
}

#[cfg(test)]
mod tests {
    use super::*;
    use optic_cgir::{CgirGraph, CgirNode};
    use optic_hir::{ConcreteGrade, Determinism, OpticSummary, OwnershipDim, PathLift, Rational};
    use optic_syntax::{BinOp, Span};
    use std::collections::BTreeMap;
    use std::sync::Arc;

    fn mk_leaf(name: &str, regions: Vec<&str>) -> (CgirNode, Arc<OpticSummary>) {
        let sum = OpticSummary {
            name: Some(name.into()),
            costate: "Entities".into(),
            focus: "f32".into(),
            lift: PathLift::default(),
            get_reads: regions.iter().map(|s| s.to_string()).collect(),
            put_reads: vec![],
            put_writes: regions.iter().map(|s| s.to_string()).collect(),
            get_grade: ConcreteGrade {
                cache: 1,
                ownership: OwnershipDim {
                    share: Rational::one(),
                    read_only: false,
                    must_use: false,
                },
            },
            put_grade: ConcreteGrade {
                cache: 1,
                ownership: OwnershipDim {
                    share: Rational::one(),
                    read_only: false,
                    must_use: false,
                },
            },
            get_determinism: Determinism::Pure,
            put_determinism: Determinism::Pure,
            serializable: true,
            provenance: Span::dummy(),
        };
        let arc = Arc::new(sum);
        let node = CgirNode::OpticLeaf {
            id: 0,
            name: name.into(),
            costate: "E".into(),
            focus: "f".into(),
            grade: arc.get_grade.clone(),
            get_fn: "".into(),
            put_fn: "".into(),
            summary: Arc::clone(&arc),
            provenance: Span::dummy(),
        };
        (node, arc)
    }

    #[test]
    fn test_detect_query_get_mode() {
        let (leaf, _) = mk_leaf("HealthView", vec!["healths"]);
        let g = CgirGraph {
            nodes: vec![
                leaf,
                CgirNode::QueryGet {
                    id: 1,
                    optic_name: "HealthView".into(),
                    costate: "entities".into(),
                    cursor: "cur".into(),
                    provenance: Span::dummy(),
                },
            ],
            roots: vec![1],
            provenance_index: BTreeMap::new(),
            resolved_optics: [("HealthView".into(), 0)].into_iter().collect(),
        };
        match detect_query_mode(&g) {
            QueryMode::Get { root } => assert_eq!(root, 1),
            _ => panic!("expected Get mode"),
        }
    }

    #[test]
    fn test_detect_query_set_mode() {
        let (leaf, _) = mk_leaf("HealthView", vec!["healths"]);
        let g = CgirGraph {
            nodes: vec![
                leaf,
                CgirNode::QuerySet {
                    id: 1,
                    optic_name: "HealthView".into(),
                    costate: "entities".into(),
                    cursor: "cur".into(),
                    value_repr: "42.5".into(),
                    provenance: Span::dummy(),
                },
            ],
            roots: vec![1],
            provenance_index: BTreeMap::new(),
            resolved_optics: [("HealthView".into(), 0)].into_iter().collect(),
        };
        match detect_query_mode(&g) {
            QueryMode::Set { root } => assert_eq!(root, 1),
            _ => panic!("expected Set mode"),
        }
    }

    #[test]
    fn test_emit_map_body_from_hir() {
        let body = HirExpr::Bin {
            op: BinOp::Sub,
            left: Box::new(HirExpr::Var("h".into(), Span::dummy())),
            right: Box::new(HirExpr::LitFloat(10.0, Span::dummy())),
            span: Span::dummy(),
        };
        assert_eq!(
            emit_map_body(&body, "h", "_h").expect("emit body"),
            "(_h - 10.0)"
        );
        let s = emit(
            &CgirGraph {
                nodes: vec![
                    mk_leaf("H", vec!["healths"]).0,
                    CgirNode::QueryMap {
                        id: 1,
                        optic_name: "H".into(),
                        costate: "e".into(),
                        cursor: "c".into(),
                        map_param: "h".into(),
                        map_body: Arc::new(body),
                        provenance: Span::dummy(),
                    },
                ],
                roots: vec![1],
                provenance_index: BTreeMap::new(),
                resolved_optics: [("H".into(), 0)].into_iter().collect(),
            },
            "r",
        )
        .expect("emit");
        assert!(s.contains("_h - 10.0") || s.contains("(_h - 10.0)"));
    }

    #[test]
    fn test_emit_rejects_hostile_optic_keyword_name() {
        let (leaf, _) = mk_leaf("fn", vec!["healths"]);
        let body = HirExpr::Var("h".into(), Span::dummy());
        let g = CgirGraph {
            nodes: vec![
                leaf,
                CgirNode::QueryMap {
                    id: 1,
                    optic_name: "fn".into(),
                    costate: "e".into(),
                    cursor: "c".into(),
                    map_param: "h".into(),
                    map_body: std::sync::Arc::new(body),
                    provenance: Span::dummy(),
                },
            ],
            roots: vec![1],
            provenance_index: BTreeMap::new(),
            resolved_optics: [("fn".into(), 0)].into_iter().collect(),
        };
        let err = emit(&g, "optic_runtime").expect_err("keyword optic name must fail emit");
        assert!(
            err.contains("reserved Rust keyword") || err.contains("invalid Rust identifier"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn test_is_valid_rust_ident_rejects_invalid() {
        assert!(is_valid_rust_ident("HealthView"));
        assert!(is_valid_rust_ident("_h"));
        assert!(!is_valid_rust_ident(""));
        assert!(!is_valid_rust_ident("9bad"));
        assert!(!is_valid_rust_ident("bad-name"));
        assert!(!is_valid_rust_ident("fn"));
        assert!(!is_valid_rust_ident("match"));
    }

    #[test]
    fn test_emit_health_get_matches_fixture_shape() {
        let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../examples/health_get.opt");
        let src = std::fs::read_to_string(&path).expect("read health_get.opt");
        let prog = optic_syntax::parse(&src, optic_syntax::SourceId(1)).expect("parse");
        let hir = optic_hir::lower(prog).expect("lower");
        let typed = optic_typeck::check(hir).expect("typeck");
        let cg = optic_cgir::build(&typed).expect("cgir");
        let graph = optic_opt::optimize(cg).expect("optimize");
        let emitted = emit(&graph, "optic_runtime").expect("emit");
        let fixture = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../fixtures/rust/health_get.rs");
        let expected = std::fs::read_to_string(&fixture).expect("fixture rust");
        for needle in ["println!(\"get: {}\", _v);", "cursor_0.arena.healths"] {
            assert!(emitted.contains(needle), "missing {needle}");
            assert!(expected.contains(needle), "fixture missing {needle}");
        }
    }

    #[test]
    fn test_emit_health_set_matches_fixture_shape() {
        let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../examples/health_set.opt");
        let src = std::fs::read_to_string(&path).expect("read health_set.opt");
        let prog = optic_syntax::parse(&src, optic_syntax::SourceId(1)).expect("parse");
        let hir = optic_hir::lower(prog).expect("lower");
        let typed = optic_typeck::check(hir).expect("typeck");
        let cg = optic_cgir::build(&typed).expect("cgir");
        let graph = optic_opt::optimize(cg).expect("optimize");
        let emitted = emit(&graph, "optic_runtime").expect("emit");
        let fixture = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../fixtures/rust/health_set.rs");
        let expected = std::fs::read_to_string(&fixture).expect("fixture rust");
        for needle in [
            "cursor_0.arena.healths[cursor_0.id] = 42.0;",
            "pub fn run_example",
        ] {
            assert!(emitted.contains(needle), "missing {needle}");
            assert!(expected.contains(needle), "fixture missing {needle}");
        }
    }

    #[test]
    fn test_emit_health_position_matches_fixture_shape() {
        let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../examples/health_position.opt");
        let src = std::fs::read_to_string(&path).expect("read health_position.opt");
        let prog = optic_syntax::parse(&src, optic_syntax::SourceId(1)).expect("parse");
        let hir = optic_hir::lower(prog).expect("lower");
        let typed = optic_typeck::check(hir).expect("typeck");
        let cg = optic_cgir::build(&typed).expect("cgir");
        let graph = optic_opt::optimize(cg).expect("optimize");
        let emitted = emit(&graph, "optic_runtime").expect("emit");
        let fixture = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../fixtures/rust/health_position.rs");
        let expected = std::fs::read_to_string(&fixture).expect("fixture rust");
        for needle in [
            "let _h = cursor_0.arena.healths[cursor_0.id];",
            "let _p = cursor_0.arena.positions[cursor_0.id];",
            "_h - 1.0",
            "_p.0 + 0.1",
            "cursor_0.arena.healths[cursor_0.id] = _h_new;",
            "cursor_0.arena.positions[cursor_0.id] = _p_new;",
        ] {
            assert!(emitted.contains(needle), "missing {needle}");
            assert!(expected.contains(needle), "fixture missing {needle}");
        }
    }

    #[test]
    fn test_emit_health_decay_matches_fixture_shape() {
        let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../examples/health_decay.opt");
        let src = std::fs::read_to_string(&path).expect("read health_decay.opt");
        let prog = optic_syntax::parse(&src, optic_syntax::SourceId(1)).expect("parse");
        let hir = optic_hir::lower(prog).expect("lower");
        let typed = optic_typeck::check(hir).expect("typeck");
        let cg = optic_cgir::build(&typed).expect("cgir");
        let graph = optic_opt::optimize(cg).expect("optimize");
        let emitted = emit(&graph, "optic_runtime").expect("emit");
        let fixture = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../fixtures/rust/health_decay.rs");
        let expected = std::fs::read_to_string(&fixture).expect("fixture rust");
        for needle in [
            "let _h = cursor_0.arena.healths[cursor_0.id];",
            "_h - 10.0",
            "cursor_0.arena.healths[cursor_0.id] =",
        ] {
            assert!(emitted.contains(needle), "missing {needle}");
            assert!(expected.contains(needle), "fixture missing {needle}");
        }
    }

    #[test]
    fn test_emit_product_map_tuple_body() {
        let (h_leaf, _) = mk_leaf("HealthView", vec!["healths"]);
        let (p_leaf, _) = mk_leaf("PositionView", vec!["positions"]);
        let body = HirExpr::Tuple(
            vec![
                HirExpr::Bin {
                    op: BinOp::Sub,
                    left: Box::new(HirExpr::Var("h".into(), Span::dummy())),
                    right: Box::new(HirExpr::LitFloat(1.0, Span::dummy())),
                    span: Span::dummy(),
                },
                HirExpr::Tuple(
                    vec![
                        HirExpr::TupleProj {
                            base: Box::new(HirExpr::Var("p".into(), Span::dummy())),
                            index: 0,
                            span: Span::dummy(),
                        },
                        HirExpr::Var("p".into(), Span::dummy()),
                    ],
                    Span::dummy(),
                ),
            ],
            Span::dummy(),
        );
        let g = CgirGraph {
            nodes: vec![
                h_leaf,
                p_leaf,
                CgirNode::Product {
                    id: 2,
                    lhs: 0,
                    rhs: 1,
                    grade: ConcreteGrade {
                        cache: 2,
                        ownership: OwnershipDim {
                            share: Rational::one(),
                            read_only: false,
                            must_use: false,
                        },
                    },
                    alias_safe: true,
                    provenance: Span::dummy(),
                },
                CgirNode::QueryMap {
                    id: 3,
                    optic_name: "combined".into(),
                    costate: "entities".into(),
                    cursor: "c".into(),
                    map_param: "h,p".into(),
                    map_body: Arc::new(body),
                    provenance: Span::dummy(),
                },
            ],
            roots: vec![3],
            provenance_index: BTreeMap::new(),
            resolved_optics: [("combined".into(), 2)].into_iter().collect(),
        };
        let s = emit(&g, "r").expect("emit product map");
        assert!(s.contains("_h - 1.0"));
        assert!(s.contains("_p.0"));
        assert!(s.contains("positions"));
    }
}
