//! optic-codegen-rust — emit exact ch. 11 loop shapes from (post-fusion) CGIR (M5).

use optic_cgir::{format_hir_expr, CgirGraph, CgirNode, NodeId};
use optic_hir::HirExpr;

enum QueryMode {
    MapDecay { root: NodeId },
    MapProduct { root: NodeId },
    Get { root: NodeId },
    Set { root: NodeId },
}

pub fn emit(graph: &CgirGraph, _runtime: &str) -> String {
    let mut out = String::with_capacity(1024);
    out.push_str("// AUTO-GENERATED by opticc (syntax->hir->typeck->cgir->opt->codegen)\n");
    out.push_str("use optic_runtime::Cursor;\n\n");

    let query_mode = detect_query_mode(graph);
    let leaf_nodes: Vec<_> = graph
        .nodes
        .iter()
        .filter_map(|n| {
            if let CgirNode::OpticLeaf { name, summary, .. } = n {
                Some((name.clone(), summary))
            } else {
                None
            }
        })
        .collect();

    let mut all_regions: Vec<String> = vec![];
    let mut leaf_names: Vec<String> = vec![];
    let mut seen = std::collections::HashSet::new();
    for (nm, sum) in &leaf_nodes {
        leaf_names.push(nm.clone());
        for r in sum
            .get_reads
            .iter()
            .chain(&sum.put_writes)
            .chain(&sum.put_reads)
        {
            if seen.insert(r.clone()) {
                all_regions.push(r.clone());
            }
        }
    }

    let est = 1024 + leaf_names.len() * 128 + all_regions.len() * 64;
    out.reserve(est.max(4096));

    out.push_str("#[derive(Debug)]\npub struct Entities {\n");
    for reg in &all_regions {
        out.push_str(&format!(
            "    pub {}: {},\n",
            region_field(reg),
            region_ty(reg)
        ));
    }
    if all_regions.is_empty() {
        out.push_str("    pub healths: Vec<f32>,\n");
    }
    out.push_str("}\n\n");

    match &query_mode {
        QueryMode::Get { root } => {
            let optic_name = query_optic_name(graph, *root);
            let field = primary_field_for_optic(graph, &optic_name);
            out.push_str("pub fn run_example(entities: &mut Entities) {\n");
            out.push_str(&format!("    let n = entities.{}.len();\n", field));
            out.push_str("    for id_0 in 0..n {\n");
            out.push_str("        let cursor_0 = Cursor::new(entities, id_0);\n");
            out.push_str(&format!(
                "        let _v = cursor_0.arena.{}[cursor_0.id];\n",
                field
            ));
            out.push_str("        println!(\"get: {}\", _v);\n");
            out.push_str("    }\n}\n\n");
        }
        QueryMode::Set { root } => {
            let CgirNode::QuerySet {
                optic_name,
                value_repr,
                ..
            } = &graph.nodes[*root as usize]
            else {
                panic!("invalid set root");
            };
            let field = primary_field_for_optic(graph, optic_name);
            let lit = f32_literal(value_repr);
            out.push_str("pub fn run_example(entities: &mut Entities) {\n");
            out.push_str(&format!("    let n = entities.{}.len();\n", field));
            out.push_str("    for id_0 in 0..n {\n");
            out.push_str("        let cursor_0 = Cursor::new(entities, id_0);\n");
            out.push_str(&format!(
                "        cursor_0.arena.{}[cursor_0.id] = {lit};\n",
                field
            ));
            out.push_str("    }\n}\n\n");
        }
        QueryMode::MapProduct { root } => {
            let CgirNode::QueryMap {
                optic_name,
                map_body,
                map_param,
                ..
            } = &graph.nodes[*root as usize]
            else {
                panic!("invalid map root");
            };
            let product_regions = product_regions_ordered(graph, optic_name);
            let regions = if product_regions.is_empty() {
                all_regions.clone()
            } else {
                product_regions
            };
            let comment_names = if leaf_names.is_empty() {
                "unknown".to_string()
            } else {
                leaf_names.join(", ")
            };
            out.push_str(&format!("// optic(fused): [{}]\n", comment_names));
            let n_field = regions
                .first()
                .map(|r| region_field(r))
                .unwrap_or_else(|| "healths".into());
            out.push_str("pub fn run_example(entities: &mut Entities) {\n");
            out.push_str(&format!("    let n = entities.{n_field}.len();\n"));
            out.push_str("    for id_0 in 0..n {\n");
            out.push_str("        let cursor_0 = Cursor::new(entities, id_0);\n");
            for reg in &regions {
                let f = region_field(reg);
                let bind = region_bind(reg);
                out.push_str(&format!(
                    "        let {bind} = cursor_0.arena.{f}[cursor_0.id];\n"
                ));
            }
            let binds: Vec<String> = regions.iter().map(|r| region_bind(r)).collect();
            let body_rust = emit_map_body_product(map_body, map_param, &binds);
            emit_product_stores(&mut out, &regions, &body_rust, map_body);
            out.push_str("    }\n}\n\n");
        }
        QueryMode::MapDecay { root } => {
            let CgirNode::QueryMap {
                map_body,
                map_param,
                ..
            } = &graph.nodes[*root as usize]
            else {
                panic!("invalid map root");
            };
            let field = all_regions
                .first()
                .map(|r| region_field(r))
                .unwrap_or_else(|| "healths".into());
            let bind = region_bind(all_regions.first().map(|s| s.as_str()).unwrap_or("healths"));
            out.push_str("pub fn run_example(entities: &mut Entities) {\n");
            out.push_str(&format!("    let n = entities.{field}.len();\n"));
            out.push_str("    for id_0 in 0..n {\n");
            out.push_str("        let cursor_0 = Cursor::new(entities, id_0);\n");
            out.push_str(&format!(
                "        let {bind} = cursor_0.arena.{field}[cursor_0.id];\n"
            ));
            let body_rust = emit_map_body(map_body, map_param, &bind);
            out.push_str(&format!(
                "        let _new = {body_rust};\n        cursor_0.arena.{field}[cursor_0.id] = _new;\n"
            ));
            out.push_str("    }\n}\n\n");
        }
    }

    out.push_str("fn main() {\n    let mut world = Entities { ");
    let mut inits = vec!["healths: vec![100.0, 80.0, 50.0]".to_string()];
    if all_regions.iter().any(|r| r.contains("pos")) {
        inits.push("positions: vec![(0.0,0.0), (1.0,1.0), (2.0,2.0)]".into());
    }
    out.push_str(&inits.join(", "));
    out.push_str(" };\n");
    out.push_str("    println!(\"before: {:?}\", world);\n");
    out.push_str("    run_example(&mut world);\n");
    out.push_str("    println!(\"after:  {:?}\", world);\n");
    out.push_str("}\n");
    out
}

fn emit_product_stores(out: &mut String, regions: &[String], body_rust: &str, map_body: &HirExpr) {
    let new_names: Vec<String> = regions
        .iter()
        .map(|r| format!("{}_new", region_bind(r)))
        .collect();
    if matches!(map_body, HirExpr::Tuple(elems, _) if elems.len() == regions.len()) {
        out.push_str("        let (");
        out.push_str(&new_names.join(", "));
        out.push_str(") = ");
        out.push_str(body_rust);
        out.push_str(";\n");
        for (reg, new_name) in regions.iter().zip(&new_names) {
            let f = region_field(reg);
            out.push_str(&format!(
                "        cursor_0.arena.{f}[cursor_0.id] = {new_name};\n"
            ));
        }
        return;
    }
    if regions.len() >= 2 && body_rust.starts_with('(') {
        out.push_str("        let (");
        out.push_str(&new_names.join(", "));
        out.push_str(") = ");
        out.push_str(body_rust);
        out.push_str(";\n");
        for (reg, new_name) in regions.iter().zip(&new_names) {
            let f = region_field(reg);
            out.push_str(&format!(
                "        cursor_0.arena.{f}[cursor_0.id] = {new_name};\n"
            ));
        }
    } else if regions.len() > 1 {
        out.push_str("        panic!(\"optic codegen: product map tuple arity mismatch\");\n");
    } else {
        let field = regions
            .first()
            .map(|r| region_field(r))
            .unwrap_or_else(|| "healths".into());
        out.push_str(&format!("        let _new = {body_rust};\n"));
        out.push_str(&format!(
            "        cursor_0.arena.{field}[cursor_0.id] = _new;\n"
        ));
    }
}

fn query_optic_name(graph: &CgirGraph, root: NodeId) -> String {
    match graph.nodes.get(root as usize) {
        Some(CgirNode::QueryGet { optic_name, .. })
        | Some(CgirNode::QuerySet { optic_name, .. })
        | Some(CgirNode::QueryMap { optic_name, .. }) => optic_name.clone(),
        _ => "unknown".into(),
    }
}

fn product_regions_ordered(graph: &CgirGraph, optic_name: &str) -> Vec<String> {
    let Some(&nid) = graph.resolved_optics.get(optic_name) else {
        return vec![];
    };
    collect_regions_from_node(graph, nid)
}

fn collect_regions_from_node(graph: &CgirGraph, nid: NodeId) -> Vec<String> {
    match graph.nodes.get(nid as usize) {
        Some(CgirNode::Product { lhs, rhs, .. }) => {
            let mut out = collect_regions_from_node(graph, *lhs);
            out.extend(collect_regions_from_node(graph, *rhs));
            out
        }
        Some(CgirNode::Compose { lhs, rhs, .. }) => {
            let mut out = collect_regions_from_node(graph, *lhs);
            out.extend(collect_regions_from_node(graph, *rhs));
            out
        }
        Some(CgirNode::OpticLeaf { summary, .. }) => summary.get_reads.clone(),
        _ => vec![],
    }
}

fn emit_map_body(body: &HirExpr, map_param: &str, load_bind: &str) -> String {
    emit_hir_expr_rust(body, map_param, load_bind, None)
}

fn emit_map_body_product(body: &HirExpr, map_param: &str, binds: &[String]) -> String {
    emit_hir_expr_rust(
        body,
        map_param,
        binds.first().map(|s| s.as_str()).unwrap_or("_v"),
        Some(binds),
    )
}

fn emit_hir_expr_rust(
    e: &HirExpr,
    map_param: &str,
    load_bind: &str,
    product_binds: Option<&[String]>,
) -> String {
    match e {
        HirExpr::LitInt(n, _) => format!("{n}.0"),
        HirExpr::LitFloat(f, _) => {
            if f.fract() == 0.0 {
                format!("{f:.1}")
            } else {
                f.to_string()
            }
        }
        HirExpr::Var(v, _) => {
            if let Some(binds) = product_binds {
                let params: Vec<&str> = map_param.split(',').map(str::trim).collect();
                if let Some(i) = params.iter().position(|p| *p == v) {
                    return binds.get(i).cloned().unwrap_or_else(|| v.clone());
                }
            }
            if v == map_param {
                load_bind.to_string()
            } else {
                v.clone()
            }
        }
        HirExpr::Bin {
            op, left, right, ..
        } => {
            let op_s = match op {
                optic_syntax::BinOp::Add => "+",
                optic_syntax::BinOp::Sub => "-",
                optic_syntax::BinOp::Mul => "*",
                optic_syntax::BinOp::Div => "/",
                _ => "+",
            };
            format!(
                "({} {} {})",
                emit_hir_expr_rust(left, map_param, load_bind, product_binds),
                op_s,
                emit_hir_expr_rust(right, map_param, load_bind, product_binds)
            )
        }
        HirExpr::Tuple(elems, _) => {
            let parts: Vec<_> = elems
                .iter()
                .map(|el| emit_hir_expr_rust(el, map_param, load_bind, product_binds))
                .collect();
            format!("({})", parts.join(", "))
        }
        HirExpr::TupleProj { base, index, .. } => {
            format!(
                "{}.{}",
                emit_hir_expr_rust(base, map_param, load_bind, product_binds),
                index
            )
        }
        HirExpr::Unsupported { reason, .. } => format!("panic!(\"{reason}\")"),
        _ => format_hir_expr(e),
    }
}

fn region_field(reg: &str) -> String {
    if reg.contains("health") {
        "healths".into()
    } else if reg.contains("pos") {
        "positions".into()
    } else {
        reg.to_string()
    }
}

fn region_bind(reg: &str) -> String {
    if reg.contains("health") {
        "_h".into()
    } else if reg.contains("pos") {
        "_p".into()
    } else {
        format!("_{reg}")
    }
}

fn region_ty(reg: &str) -> &'static str {
    if reg.contains("pos") {
        "Vec<(f32, f32)>"
    } else {
        "Vec<f32>"
    }
}

fn primary_field_for_optic(graph: &CgirGraph, name: &str) -> String {
    graph
        .nodes
        .iter()
        .find_map(|n| {
            if let CgirNode::OpticLeaf {
                name: leaf_name,
                summary,
                ..
            } = n
            {
                if leaf_name == name {
                    return summary.get_reads.first().map(|r| region_field(r));
                }
            }
            None
        })
        .unwrap_or_else(|| "healths".into())
}

fn f32_literal(value: &str) -> String {
    if value.contains('.') {
        value.to_string()
    } else {
        format!("{value}.0")
    }
}

fn detect_query_mode(graph: &CgirGraph) -> QueryMode {
    let has_product = graph
        .nodes
        .iter()
        .any(|n| matches!(n, CgirNode::Product { .. } | CgirNode::FusedLoop { .. }));

    for &root in &graph.roots {
        if let Some(node) = graph.nodes.get(root as usize) {
            return match node {
                CgirNode::QueryGet { .. } => QueryMode::Get { root },
                CgirNode::QuerySet { .. } => QueryMode::Set { root },
                CgirNode::QueryMap { .. } => {
                    if has_product {
                        QueryMode::MapProduct { root }
                    } else {
                        QueryMode::MapDecay { root }
                    }
                }
                _ => continue,
            };
        }
    }
    QueryMode::MapDecay { root: 0 }
}

#[cfg(test)]
mod tests {
    use super::*;
    use optic_cgir::{CgirGraph, CgirNode};
    use optic_hir::{ConcreteGrade, Determinism, OpticSummary, OwnershipDim, PathLift, Rational};
    use optic_syntax::{BinOp, Span};
    use std::collections::BTreeMap;
    use std::sync::Arc;

    fn mk_leaf(name: &str, regions: Vec<&str>) -> (CgirNode, Arc<OpticSummary>) {
        let sum = OpticSummary {
            name: Some(name.into()),
            costate: "Entities".into(),
            focus: "f32".into(),
            lift: PathLift::default(),
            get_reads: regions.iter().map(|s| s.to_string()).collect(),
            put_reads: vec![],
            put_writes: regions.iter().map(|s| s.to_string()).collect(),
            get_grade: ConcreteGrade {
                cache: 1,
                ownership: OwnershipDim {
                    share: Rational::one(),
                    read_only: false,
                    must_use: false,
                },
            },
            put_grade: ConcreteGrade {
                cache: 1,
                ownership: OwnershipDim {
                    share: Rational::one(),
                    read_only: false,
                    must_use: false,
                },
            },
            get_determinism: Determinism::Pure,
            put_determinism: Determinism::Pure,
            serializable: true,
            provenance: Span::dummy(),
        };
        let arc = Arc::new(sum);
        let node = CgirNode::OpticLeaf {
            id: 0,
            name: name.into(),
            costate: "E".into(),
            focus: "f".into(),
            grade: arc.get_grade.clone(),
            get_fn: "".into(),
            put_fn: "".into(),
            summary: Arc::clone(&arc),
            provenance: Span::dummy(),
        };
        (node, arc)
    }

    #[test]
    fn test_detect_query_get_mode() {
        let (leaf, _) = mk_leaf("HealthView", vec!["healths"]);
        let g = CgirGraph {
            nodes: vec![
                leaf,
                CgirNode::QueryGet {
                    id: 1,
                    optic_name: "HealthView".into(),
                    costate: "entities".into(),
                    cursor: "cur".into(),
                    provenance: Span::dummy(),
                },
            ],
            roots: vec![1],
            provenance_index: BTreeMap::new(),
            resolved_optics: [("HealthView".into(), 0)].into_iter().collect(),
        };
        match detect_query_mode(&g) {
            QueryMode::Get { root } => assert_eq!(root, 1),
            _ => panic!("expected Get mode"),
        }
    }

    #[test]
    fn test_detect_query_set_mode() {
        let (leaf, _) = mk_leaf("HealthView", vec!["healths"]);
        let g = CgirGraph {
            nodes: vec![
                leaf,
                CgirNode::QuerySet {
                    id: 1,
                    optic_name: "HealthView".into(),
                    costate: "entities".into(),
                    cursor: "cur".into(),
                    value_repr: "42.5".into(),
                    provenance: Span::dummy(),
                },
            ],
            roots: vec![1],
            provenance_index: BTreeMap::new(),
            resolved_optics: [("HealthView".into(), 0)].into_iter().collect(),
        };
        match detect_query_mode(&g) {
            QueryMode::Set { root } => assert_eq!(root, 1),
            _ => panic!("expected Set mode"),
        }
    }

    #[test]
    fn test_emit_map_body_from_hir() {
        let body = HirExpr::Bin {
            op: BinOp::Sub,
            left: Box::new(HirExpr::Var("h".into(), Span::dummy())),
            right: Box::new(HirExpr::LitFloat(10.0, Span::dummy())),
            span: Span::dummy(),
        };
        assert_eq!(emit_map_body(&body, "h", "_h"), "(_h - 10.0)");
        let s = emit(
            &CgirGraph {
                nodes: vec![
                    mk_leaf("H", vec!["healths"]).0,
                    CgirNode::QueryMap {
                        id: 1,
                        optic_name: "H".into(),
                        costate: "e".into(),
                        cursor: "c".into(),
                        map_param: "h".into(),
                        map_body: body,
                        provenance: Span::dummy(),
                    },
                ],
                roots: vec![1],
                provenance_index: BTreeMap::new(),
                resolved_optics: [("H".into(), 0)].into_iter().collect(),
            },
            "r",
        );
        assert!(s.contains("_h - 10.0") || s.contains("(_h - 10.0)"));
    }

    #[test]
    fn test_emit_product_map_tuple_body() {
        let (h_leaf, _) = mk_leaf("HealthView", vec!["healths"]);
        let (p_leaf, _) = mk_leaf("PositionView", vec!["positions"]);
        let body = HirExpr::Tuple(
            vec![
                HirExpr::Bin {
                    op: BinOp::Sub,
                    left: Box::new(HirExpr::Var("h".into(), Span::dummy())),
                    right: Box::new(HirExpr::LitFloat(1.0, Span::dummy())),
                    span: Span::dummy(),
                },
                HirExpr::Tuple(
                    vec![
                        HirExpr::TupleProj {
                            base: Box::new(HirExpr::Var("p".into(), Span::dummy())),
                            index: 0,
                            span: Span::dummy(),
                        },
                        HirExpr::Var("p".into(), Span::dummy()),
                    ],
                    Span::dummy(),
                ),
            ],
            Span::dummy(),
        );
        let g = CgirGraph {
            nodes: vec![
                h_leaf,
                p_leaf,
                CgirNode::Product {
                    id: 2,
                    lhs: 0,
                    rhs: 1,
                    grade: ConcreteGrade {
                        cache: 2,
                        ownership: OwnershipDim {
                            share: Rational::one(),
                            read_only: false,
                            must_use: false,
                        },
                    },
                    alias_safe: true,
                    provenance: Span::dummy(),
                },
                CgirNode::QueryMap {
                    id: 3,
                    optic_name: "combined".into(),
                    costate: "entities".into(),
                    cursor: "c".into(),
                    map_param: "h,p".into(),
                    map_body: body,
                    provenance: Span::dummy(),
                },
            ],
            roots: vec![3],
            provenance_index: BTreeMap::new(),
            resolved_optics: [("combined".into(), 2)].into_iter().collect(),
        };
        let s = emit(&g, "r");
        assert!(s.contains("_h - 1.0"));
        assert!(s.contains("_p.0"));
        assert!(s.contains("positions"));
    }
}
