//! optic-codegen-rust — emit exact ch. 11 loop shapes from (post-fusion) CGIR (M5).

use optic_cgir::{compose_leaf_chain, CgirGraph, CgirNode, NodeId};
use optic_hir::{HirExpr, RegionMap};

enum QueryMode {
    MapDecay { root: NodeId },
    MapProduct { root: NodeId },
    MapCompose { root: NodeId, compose_id: NodeId },
    FusedCompose { root: NodeId },
    Get { root: NodeId },
    Set { root: NodeId },
}

const RUST_KEYWORDS: &[&str] = &[
    "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum", "extern",
    "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub",
    "ref", "return", "self", "Self", "static", "struct", "super", "trait", "true", "type",
    "unsafe", "use", "where", "while",
];

/// Reject user-derived names that would emit invalid Rust identifiers.
fn is_valid_rust_ident(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !first.is_ascii_alphabetic() && first != '_' {
        return false;
    }
    if !chars.all(|c| c.is_ascii_alphanumeric() || c == '_') {
        return false;
    }
    !RUST_KEYWORDS.contains(&name)
}

fn validate_user_ident(name: &str, context: &str) -> Result<(), String> {
    if is_valid_rust_ident(name) {
        Ok(())
    } else if RUST_KEYWORDS.contains(&name) {
        Err(format!("reserved Rust keyword for {context}: {name:?}"))
    } else {
        Err(format!("invalid Rust identifier for {context}: {name:?}"))
    }
}

pub fn emit(graph: &CgirGraph, _runtime: &str) -> Result<String, String> {
    let mut out = String::with_capacity(1024);
    out.push_str("// AUTO-GENERATED by opticc (syntax->hir->typeck->cgir->opt->codegen)\n");
    out.push_str("use optic_runtime::Cursor;\n\n");

    let query_mode = detect_query_mode(graph)?;
    let struct_name = costate_struct_name(graph);
    let leaf_nodes: Vec<_> = graph
        .nodes
        .iter()
        .filter_map(|n| {
            if let CgirNode::OpticLeaf { name, summary, .. } = n {
                Some((name.clone(), summary))
            } else {
                None
            }
        })
        .collect();

    let mut all_regions: Vec<String> = vec![];
    let mut leaf_names: Vec<String> = vec![];
    let mut seen = std::collections::HashSet::new();
    for (nm, sum) in &leaf_nodes {
        validate_user_ident(nm, "optic name")?;
        leaf_names.push(nm.clone());
        for r in sum
            .get_reads
            .iter()
            .chain(&sum.put_writes)
            .chain(&sum.put_reads)
        {
            if seen.insert(r.clone()) {
                all_regions.push(r.clone());
            }
        }
    }

    let est = 1024 + leaf_names.len() * 128 + all_regions.len() * 64;
    out.reserve(est.max(4096));

    emit_record_types(&mut out, &graph.region_map, &struct_name)?;
    out.push_str(&format!("#[derive(Debug)]\npub struct {struct_name} {{\n"));
    if graph.region_map.columns.is_empty() {
        return Err("codegen: region_map has no columns from data decl".into());
    }
    for (col_name, info) in &graph.region_map.columns {
        validate_user_ident(col_name, "region field")?;
        optic_hir::validate_rust_type(&info.rust_ty)?;
        out.push_str(&format!("    pub {}: {},\n", col_name, info.rust_ty));
    }
    out.push_str("}\n\n");

    match &query_mode {
        QueryMode::Get { root } => {
            let optic_name = query_optic_name(graph, *root)?;
            let field = primary_field_for_optic(graph, &optic_name)?;
            out.push_str(&format!(
                "pub fn run_example(entities: &mut {struct_name}) {{\n"
            ));
            out.push_str(&format!("    let n = entities.{}.len();\n", field));
            out.push_str("    for id_0 in 0..n {\n");
            out.push_str("        let cursor_0 = Cursor::new(entities, id_0);\n");
            out.push_str(&format!(
                "        let _v = cursor_0.arena.{}[cursor_0.id];\n",
                field
            ));
            out.push_str("        println!(\"get: {}\", _v);\n");
            out.push_str("    }\n}\n\n");
        }
        QueryMode::Set { root } => {
            let CgirNode::QuerySet {
                optic_name,
                value_repr,
                ..
            } = &graph.nodes[*root as usize]
            else {
                return Err(format!(
                    "invalid set root: expected QuerySet at node {root}"
                ));
            };
            let field = primary_field_for_optic(graph, optic_name)?;
            let lit = validate_f32_literal(value_repr)?;
            out.push_str(&format!(
                "pub fn run_example(entities: &mut {struct_name}) {{\n"
            ));
            out.push_str(&format!("    let n = entities.{}.len();\n", field));
            out.push_str("    for id_0 in 0..n {\n");
            out.push_str("        let cursor_0 = Cursor::new(entities, id_0);\n");
            out.push_str(&format!(
                "        cursor_0.arena.{}[cursor_0.id] = {lit};\n",
                field
            ));
            out.push_str("    }\n}\n\n");
        }
        QueryMode::MapProduct { root } => {
            let CgirNode::QueryMap {
                optic_name,
                map_body,
                map_param,
                ..
            } = &graph.nodes[*root as usize]
            else {
                return Err("invalid map root".into());
            };
            let regions = product_regions_ordered(graph, optic_name)?;
            let comment_names = if leaf_names.is_empty() {
                "unknown".to_string()
            } else {
                leaf_names.join(", ")
            };
            out.push_str(&format!("// optic(fused): [{}]\n", comment_names));
            let n_field = regions
                .first()
                .map(|r| lookup_region_field(&graph.region_map, r))
                .transpose()?
                .ok_or_else(|| "product map requires at least one region".to_string())?;
            out.push_str(&format!(
                "pub fn run_example(entities: &mut {struct_name}) {{\n"
            ));
            out.push_str(&format!("    let n = entities.{n_field}.len();\n"));
            for reg in regions.iter().skip(1) {
                let f = lookup_region_field(&graph.region_map, reg)?;
                out.push_str(&format!("    assert_eq!(n, entities.{f}.len());\n"));
            }
            out.push_str("    for id_0 in 0..n {\n");
            out.push_str("        let cursor_0 = Cursor::new(entities, id_0);\n");
            for reg in &regions {
                let f = lookup_region_field(&graph.region_map, reg)?;
                let bind = lookup_region_bind(&graph.region_map, reg)?;
                out.push_str(&format!(
                    "        let {bind} = cursor_0.arena.{f}[cursor_0.id];\n"
                ));
            }
            let binds: Vec<String> = regions
                .iter()
                .map(|r| lookup_region_bind(&graph.region_map, r))
                .collect::<Result<_, _>>()?;
            for p in map_param
                .split(',')
                .map(str::trim)
                .filter(|s| !s.is_empty())
            {
                validate_user_ident(p, "map parameter")?;
            }
            let body_rust = emit_map_body_product(map_body.as_ref(), map_param, &binds)?;
            emit_product_stores(&mut out, graph, &regions, &body_rust, map_body.as_ref())?;
            out.push_str("    }\n}\n\n");
        }
        QueryMode::MapDecay { root } => {
            let CgirNode::QueryMap {
                map_body,
                map_param,
                ..
            } = &graph.nodes[*root as usize]
            else {
                return Err("invalid map root".into());
            };
            let field = all_regions
                .first()
                .map(|r| lookup_region_field(&graph.region_map, r))
                .transpose()?
                .ok_or_else(|| "map decay requires at least one read region".to_string())?;
            let bind = lookup_region_bind(
                &graph.region_map,
                all_regions.first().expect("non-empty all_regions"),
            )?;
            out.push_str(&format!(
                "pub fn run_example(entities: &mut {struct_name}) {{\n"
            ));
            out.push_str(&format!("    let n = entities.{field}.len();\n"));
            out.push_str("    for id_0 in 0..n {\n");
            out.push_str("        let cursor_0 = Cursor::new(entities, id_0);\n");
            out.push_str(&format!(
                "        let {bind} = cursor_0.arena.{field}[cursor_0.id];\n"
            ));
            validate_user_ident(map_param, "map parameter")?;
            let body_rust = emit_map_body(map_body.as_ref(), map_param, &bind)?;
            out.push_str(&format!(
                "        let _new = {body_rust};\n        cursor_0.arena.{field}[cursor_0.id] = _new;\n"
            ));
            out.push_str("    }\n}\n\n");
        }
        QueryMode::MapCompose { root, compose_id } => {
            emit_compose_map(&mut out, graph, *root, *compose_id, &struct_name)?;
        }
        QueryMode::FusedCompose { root } => {
            emit_fused_compose_loop(&mut out, graph, *root, &leaf_names, &struct_name)?;
        }
    }

    out.push_str(&format!(
        "fn main() {{\n    let mut world = {struct_name} {{ "
    ));
    let mut inits = vec![];
    if graph.region_map.columns.is_empty() {
        return Err("codegen: region_map has no columns from data decl".into());
    }
    for (col, info) in &graph.region_map.columns {
        let init = column_init_value(&graph.region_map, col, info.element_ty.as_deref())?;
        inits.push(format!("{col}: {init}"));
    }
    if inits.is_empty() {
        return Err("codegen: cannot synthesize main() initializer without data columns".into());
    }
    out.push_str(&inits.join(", "));
    out.push_str(" };\n");
    out.push_str("    println!(\"before: {:?}\", world);\n");
    out.push_str("    run_example(&mut world);\n");
    out.push_str("    println!(\"after:  {:?}\", world);\n");
    out.push_str("}\n");
    Ok(out)
}

fn emit_product_stores(
    out: &mut String,
    graph: &CgirGraph,
    regions: &[String],
    body_rust: &str,
    map_body: &HirExpr,
) -> Result<(), String> {
    let new_names: Vec<String> = regions
        .iter()
        .map(|r| lookup_region_bind(&graph.region_map, r).map(|b| format!("{b}_new")))
        .collect::<Result<_, _>>()?;
    if matches!(map_body, HirExpr::Tuple(elems, _) if elems.len() == regions.len()) {
        out.push_str("        let (");
        out.push_str(&new_names.join(", "));
        out.push_str(") = ");
        out.push_str(body_rust);
        out.push_str(";\n");
        for (reg, new_name) in regions.iter().zip(&new_names) {
            let f = lookup_region_field(&graph.region_map, reg)?;
            out.push_str(&format!(
                "        cursor_0.arena.{f}[cursor_0.id] = {new_name};\n"
            ));
        }
        return Ok(());
    }
    if regions.len() > 1 {
        return Err(format!(
            "product map tuple arity mismatch: {} regions, body {:?}",
            regions.len(),
            map_body
        ));
    } else {
        let field = regions
            .first()
            .map(|r| lookup_region_field(&graph.region_map, r))
            .transpose()?
            .ok_or_else(|| "product store requires a region".to_string())?;
        out.push_str(&format!("        let _new = {body_rust};\n"));
        out.push_str(&format!(
            "        cursor_0.arena.{field}[cursor_0.id] = _new;\n"
        ));
    }
    Ok(())
}

fn query_optic_name(graph: &CgirGraph, root: NodeId) -> Result<String, String> {
    match graph.nodes.get(root as usize) {
        Some(CgirNode::QueryGet { optic_name, .. })
        | Some(CgirNode::QuerySet { optic_name, .. })
        | Some(CgirNode::QueryMap { optic_name, .. }) => Ok(optic_name.clone()),
        _ => Err(format!(
            "invalid query root at node {root}: expected QueryGet/Set/Map"
        )),
    }
}

fn product_regions_ordered(graph: &CgirGraph, optic_name: &str) -> Result<Vec<String>, String> {
    let Some(&nid) = graph.resolved_optics.get(optic_name) else {
        return Err(format!(
            "product map optic `{optic_name}` not resolved in CGIR graph"
        ));
    };
    let regions = collect_regions_from_node(graph, nid);
    if regions.is_empty() {
        return Err(format!(
            "product map optic `{optic_name}` has no regions from product spine"
        ));
    }
    Ok(regions)
}

fn collect_regions_from_node(graph: &CgirGraph, nid: NodeId) -> Vec<String> {
    match graph.nodes.get(nid as usize) {
        Some(CgirNode::ProductFlat { children, .. }) => children
            .iter()
            .flat_map(|&cid| collect_regions_from_node(graph, cid))
            .collect(),
        Some(CgirNode::Product { lhs, rhs, .. }) => {
            let mut out = collect_regions_from_node(graph, *lhs);
            out.extend(collect_regions_from_node(graph, *rhs));
            out
        }
        Some(CgirNode::Compose { lhs, rhs, .. }) => {
            let mut out = collect_regions_from_node(graph, *lhs);
            out.extend(collect_regions_from_node(graph, *rhs));
            out
        }
        Some(CgirNode::OpticLeaf { summary, .. }) => summary.get_reads.clone(),
        _ => vec![],
    }
}

fn emit_map_body(body: &HirExpr, map_param: &str, load_bind: &str) -> Result<String, String> {
    emit_hir_expr_rust(body, map_param, load_bind, None)
}

fn emit_map_body_product(
    body: &HirExpr,
    map_param: &str,
    binds: &[String],
) -> Result<String, String> {
    let load_bind = binds
        .first()
        .map(|s| s.as_str())
        .ok_or_else(|| "product map requires at least one region bind".to_string())?;
    emit_hir_expr_rust(body, map_param, load_bind, Some(binds))
}

fn emit_hir_expr_rust(
    e: &HirExpr,
    map_param: &str,
    load_bind: &str,
    product_binds: Option<&[String]>,
) -> Result<String, String> {
    match e {
        HirExpr::LitInt(n, _) => Ok(format!("{n}.0")),
        HirExpr::LitFloat(f, _) => Ok(if f.fract() == 0.0 {
            format!("{f:.1}")
        } else {
            f.to_string()
        }),
        HirExpr::Var(v, _) => {
            validate_user_ident(v, "map variable")?;
            if let Some(binds) = product_binds {
                let params: Vec<&str> = map_param.split(',').map(str::trim).collect();
                if let Some(i) = params.iter().position(|p| *p == v) {
                    return binds.get(i).cloned().ok_or_else(|| {
                        format!(
                            "product map param `{v}` index {i} out of range ({} binds)",
                            binds.len()
                        )
                    });
                }
            }
            Ok(if v == map_param {
                load_bind.to_string()
            } else {
                v.clone()
            })
        }
        HirExpr::Paren(inner, _) => {
            let inner_rust = emit_hir_expr_rust(inner, map_param, load_bind, product_binds)?;
            Ok(format!("({inner_rust})"))
        }
        HirExpr::Bin {
            op, left, right, ..
        } => {
            let op_s = match op {
                optic_syntax::BinOp::Add => "+",
                optic_syntax::BinOp::Sub => "-",
                optic_syntax::BinOp::Mul => "*",
                optic_syntax::BinOp::Div => "/",
                other => {
                    return Err(format!(
                        "unsupported binary operator in map body: {other:?}"
                    ));
                }
            };
            Ok(format!(
                "{} {} {}",
                emit_hir_expr_rust(left, map_param, load_bind, product_binds)?,
                op_s,
                emit_hir_expr_rust(right, map_param, load_bind, product_binds)?
            ))
        }
        HirExpr::Tuple(elems, _) => {
            let parts: Vec<_> = elems
                .iter()
                .map(|el| emit_hir_expr_rust(el, map_param, load_bind, product_binds))
                .collect::<Result<_, _>>()?;
            Ok(format!("({})", parts.join(", ")))
        }
        HirExpr::TupleProj { base, index, .. } => Ok(format!(
            "{}.{}",
            emit_hir_expr_rust(base, map_param, load_bind, product_binds)?,
            index
        )),
        HirExpr::Unsupported { reason, .. } => Err(format!("unsupported map body: {reason}")),
        other => Err(format!("unsupported HirExpr in map body emit: {other:?}")),
    }
}

fn lookup_region_field(map: &RegionMap, reg: &str) -> Result<String, String> {
    map.region_field(reg)
}

fn lookup_region_bind(map: &RegionMap, reg: &str) -> Result<String, String> {
    map.region_bind(reg)
}

fn emit_record_types(out: &mut String, map: &RegionMap, costate_name: &str) -> Result<(), String> {
    for (type_name, fields) in &map.record_fields {
        if type_name == costate_name {
            continue;
        }
        validate_user_ident(type_name, "record type name")?;
        out.push_str(&format!(
            "#[derive(Debug, Clone, Copy, Default)]\npub struct {type_name} {{\n"
        ));
        for (fname, fty) in fields {
            validate_user_ident(fname, "record field")?;
            optic_hir::validate_rust_type(fty)?;
            out.push_str(&format!("    pub {fname}: {fty},\n"));
        }
        out.push_str("}\n\n");
    }
    Ok(())
}

fn column_init_value(
    map: &RegionMap,
    _col: &str,
    element_ty: Option<&str>,
) -> Result<String, String> {
    // Harness fixture convention: three demo rows for acceptance examples (health_*, position_*).
    match element_ty {
        Some("f32") => Ok("vec![100.0, 80.0, 50.0]".into()),
        Some("i32") | Some("u32") => Ok("vec![0, 0, 0]".into()),
        Some("(f32, f32)") => Ok("vec![(0.0,0.0), (1.0,1.0), (2.0,2.0)]".into()),
        Some(record) if map.record_fields.contains_key(record) => {
            let fields = &map.record_fields[record];
            let rows: Vec<String> = (0..3)
                .map(|i| -> Result<String, String> {
                    let field_inits: Vec<String> = fields
                        .iter()
                        .map(|(fname, fty)| -> Result<String, String> {
                            let v = default_scalar_init_at(fty, i, map)?;
                            Ok(format!("{fname}: {v}"))
                        })
                        .collect::<Result<_, _>>()?;
                    Ok(format!("{record} {{ {} }}", field_inits.join(", ")))
                })
                .collect::<Result<_, _>>()?;
            Ok(format!("vec![{}]", rows.join(", ")))
        }
        Some(ty) => Ok(format!("Vec::<{ty}>::new()")),
        None => Ok("Vec::new()".into()),
    }
}

fn default_scalar_init_at(ty: &str, row: usize, map: &RegionMap) -> Result<String, String> {
    optic_hir::validate_rust_type(ty)?;
    let f = row as f32;
    Ok(match ty {
        "f32" => format!("{f:.1}"),
        "i32" | "u32" => format!("{row}"),
        "(f32, f32)" => format!("({f:.1}, {f:.1})"),
        other if other.starts_with('(') => {
            let n = ty.matches(',').count() + 1;
            format!(
                "({})",
                (0..n)
                    .map(|_| format!("{f:.1}"))
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        }
        other if map.record_fields.contains_key(other) => {
            format!("{other} {{ ..Default::default() }}")
        }
        _ => "Default::default()".into(),
    })
}

fn primary_field_for_optic(graph: &CgirGraph, name: &str) -> Result<String, String> {
    let reg = graph
        .nodes
        .iter()
        .find_map(|n| {
            if let CgirNode::OpticLeaf {
                name: leaf_name,
                summary,
                ..
            } = n
            {
                if leaf_name == name {
                    return summary.get_reads.first().cloned();
                }
            }
            None
        })
        .ok_or_else(|| format!("optic `{name}` has no get_reads region"))?;
    lookup_region_field(&graph.region_map, &reg)
}

fn f32_literal(value: &str) -> String {
    if value.contains('.') {
        value.to_string()
    } else {
        format!("{value}.0")
    }
}

fn validate_f32_literal(value_repr: &str) -> Result<String, String> {
    let trimmed = value_repr.trim();
    if trimmed.is_empty() {
        return Err("empty f32 literal in set value".into());
    }
    if !trimmed
        .chars()
        .all(|c| c.is_ascii_digit() || matches!(c, '.' | '-' | '+'))
    {
        return Err(format!("invalid f32 literal in set value: {trimmed:?}"));
    }
    trimmed
        .parse::<f64>()
        .map_err(|_| format!("invalid f32 literal in set value: {trimmed:?}"))?;
    Ok(f32_literal(trimmed))
}

fn costate_struct_name(graph: &CgirGraph) -> String {
    let raw = graph
        .roots
        .first()
        .and_then(|&r| graph.nodes.get(r as usize))
        .map(|n| match n {
            CgirNode::QueryGet { costate, .. }
            | CgirNode::QuerySet { costate, .. }
            | CgirNode::QueryMap { costate, .. } => costate.clone(),
            CgirNode::FusedLoop { costate, .. } => costate.clone(),
            _ => "entities".into(),
        })
        .unwrap_or_else(|| "entities".into());
    if raw.is_empty() {
        return "Entities".into();
    }
    let mut chars = raw.chars();
    let first = chars.next().unwrap().to_ascii_uppercase().to_string();
    first + chars.as_str()
}

fn validate_leaf_params(leaf: &CgirNode) -> Result<(), String> {
    let CgirNode::OpticLeaf {
        get_param,
        put_state_param,
        put_value_param,
        ..
    } = leaf
    else {
        return Err("validate_leaf_params expects OpticLeaf".into());
    };
    validate_user_ident(get_param, "optic get parameter")?;
    if let Some(s) = put_state_param {
        validate_user_ident(s, "optic put state parameter")?;
    }
    if let Some(v) = put_value_param {
        validate_user_ident(v, "optic put value parameter")?;
    }
    Ok(())
}

/// Structural HirExpr substitution (same pattern as map fusion in optic-opt).
fn substitute_hir_var(e: &HirExpr, name: &str, repl: &str) -> HirExpr {
    match e {
        HirExpr::Var(v, sp) if v == name => HirExpr::Var(repl.into(), *sp),
        HirExpr::Var(v, sp) => HirExpr::Var(v.clone(), *sp),
        HirExpr::LitInt(n, sp) => HirExpr::LitInt(*n, *sp),
        HirExpr::LitFloat(f, sp) => HirExpr::LitFloat(*f, *sp),
        HirExpr::Bin {
            op,
            left,
            right,
            span,
        } => HirExpr::Bin {
            op: *op,
            left: Box::new(substitute_hir_var(left, name, repl)),
            right: Box::new(substitute_hir_var(right, name, repl)),
            span: *span,
        },
        HirExpr::Paren(inner, sp) => {
            HirExpr::Paren(Box::new(substitute_hir_var(inner, name, repl)), *sp)
        }
        HirExpr::Tuple(elems, sp) => HirExpr::Tuple(
            elems
                .iter()
                .map(|el| substitute_hir_var(el, name, repl))
                .collect(),
            *sp,
        ),
        HirExpr::TupleProj { base, index, span } => HirExpr::TupleProj {
            base: Box::new(substitute_hir_var(base, name, repl)),
            index: *index,
            span: *span,
        },
        HirExpr::CursorIndex {
            cursor,
            field,
            span,
        } => HirExpr::CursorIndex {
            cursor: cursor.clone(),
            field: field.clone(),
            span: *span,
        },
        HirExpr::CursorField {
            cursor,
            field,
            span,
        } => HirExpr::CursorField {
            cursor: cursor.clone(),
            field: field.clone(),
            span: *span,
        },
        HirExpr::FocusField { param, path, span } => {
            if param == name {
                HirExpr::FocusField {
                    param: repl.into(),
                    path: path.clone(),
                    span: *span,
                }
            } else {
                HirExpr::FocusField {
                    param: param.clone(),
                    path: path.clone(),
                    span: *span,
                }
            }
        }
        HirExpr::Unsupported { reason, span } => HirExpr::Unsupported {
            reason: reason.clone(),
            span: *span,
        },
    }
}

fn substitute_hir_vars(e: &HirExpr, subs: &[(&str, &str)]) -> HirExpr {
    let mut out = e.clone();
    for (name, repl) in subs {
        out = substitute_hir_var(&out, name, repl);
    }
    out
}

fn emit_pure_hir_expr(e: &HirExpr, cursor: &str) -> Result<String, String> {
    match e {
        HirExpr::LitInt(n, _) => Ok(format!("{n}.0")),
        HirExpr::LitFloat(f, _) => Ok(if f.fract() == 0.0 {
            format!("{f:.1}")
        } else {
            f.to_string()
        }),
        HirExpr::Var(v, _) => {
            validate_user_ident(v, "optic body variable")?;
            Ok(v.clone())
        }
        HirExpr::Paren(inner, _) => {
            let inner_rust = emit_pure_hir_expr(inner, cursor)?;
            Ok(format!("({inner_rust})"))
        }
        HirExpr::Bin {
            op, left, right, ..
        } => {
            let op_s = match op {
                optic_syntax::BinOp::Add => "+",
                optic_syntax::BinOp::Sub => "-",
                optic_syntax::BinOp::Mul => "*",
                optic_syntax::BinOp::Div => "/",
                other => {
                    return Err(format!(
                        "unsupported binary operator in optic body: {other:?}"
                    ));
                }
            };
            Ok(format!(
                "{} {} {}",
                emit_pure_hir_expr(left, cursor)?,
                op_s,
                emit_pure_hir_expr(right, cursor)?
            ))
        }
        HirExpr::CursorIndex { field, .. } => {
            validate_user_ident(field, "region field")?;
            Ok(format!("{cursor}.arena.{field}[{cursor}.id]"))
        }
        HirExpr::CursorField { field, .. } => {
            validate_user_ident(field, "region field")?;
            Ok(format!("{cursor}.arena.{field}"))
        }
        HirExpr::Tuple(elems, _) => {
            let parts: Vec<_> = elems
                .iter()
                .map(|el| emit_pure_hir_expr(el, cursor))
                .collect::<Result<_, _>>()?;
            Ok(format!("({})", parts.join(", ")))
        }
        HirExpr::TupleProj { base, index, .. } => {
            Ok(format!("{}.{}", emit_pure_hir_expr(base, cursor)?, index))
        }
        HirExpr::FocusField { param, path, .. } => {
            if path.is_empty() {
                return Err("empty focus field path in optic body".into());
            }
            Ok(format!("{param}.{}", path.join(".")))
        }
        HirExpr::Unsupported { reason, .. } => Err(format!("unsupported optic body: {reason}")),
    }
}

fn emit_compose_map(
    out: &mut String,
    graph: &CgirGraph,
    root: NodeId,
    compose_id: NodeId,
    struct_name: &str,
) -> Result<(), String> {
    let CgirNode::QueryMap {
        map_body,
        map_param,
        ..
    } = &graph.nodes[root as usize]
    else {
        return Err("invalid compose map root".into());
    };
    // Unfused compose intentionally mirrors fused loop semantics (ch10); equivalence tests rely on this.
    emit_compose_chain_loop(
        out,
        graph,
        compose_id,
        map_body.as_ref(),
        map_param,
        None,
        struct_name,
    )
}

fn emit_fused_compose_loop(
    out: &mut String,
    graph: &CgirGraph,
    root: NodeId,
    leaf_names: &[String],
    struct_name: &str,
) -> Result<(), String> {
    let CgirNode::FusedLoop {
        compose_body,
        original_ids,
        ..
    } = &graph.nodes[root as usize]
    else {
        return Err("invalid fused compose root".into());
    };
    let body = compose_body
        .as_ref()
        .ok_or_else(|| "FusedCompose missing compose_body".to_string())?;
    let names = fused_provenance_names(graph, original_ids, leaf_names);
    // Fused compose shares the same loop body shape as unfused MapCompose (ch10 semantic preservation).
    emit_compose_chain_loop(
        out,
        graph,
        body.compose_id,
        body.map_body.as_ref(),
        &body.map_param,
        Some(&names),
        struct_name,
    )
}

/// Emit get/put spine for a (possibly nested) Compose tree + map body.
fn emit_compose_chain_loop(
    out: &mut String,
    graph: &CgirGraph,
    compose_id: NodeId,
    map_body: &HirExpr,
    map_param: &str,
    fused_names: Option<&str>,
    struct_name: &str,
) -> Result<(), String> {
    let chain = compose_leaf_chain(graph, compose_id)
        .ok_or_else(|| format!("compose {compose_id} is not a leaf spine"))?;
    if chain.is_empty() {
        return Err("compose chain is empty".into());
    }
    let n_field = compose_primary_field(graph, chain[0])?;
    if let Some(names) = fused_names {
        out.push_str(&format!("// optic(fused): [{names}]\n"));
    }
    out.push_str(&format!(
        "pub fn run_example(entities: &mut {struct_name}) {{\n"
    ));
    out.push_str(&format!("    let n = entities.{n_field}.len();\n"));
    out.push_str("    for id_0 in 0..n {\n");
    out.push_str("        let cursor_0 = Cursor::new(entities, id_0);\n");
    validate_user_ident(map_param, "map parameter")?;

    let needs_mut = chain
        .iter()
        .skip(1)
        .any(|&leaf| is_focus_relative_put(graph, leaf));
    let mut binds: Vec<String> = vec![];
    for (i, &leaf) in chain.iter().enumerate() {
        let focus = if i == 0 {
            None
        } else {
            Some(binds[i - 1].as_str())
        };
        let expr = emit_leaf_get(graph, leaf, "cursor_0", focus)?;
        let bind = format!("_c{i}");
        let mut_kw = if needs_mut && i < chain.len() - 1 {
            "mut "
        } else if needs_mut && i == 0 {
            "mut "
        } else {
            ""
        };
        out.push_str(&format!("        let {mut_kw}{bind} = {expr};\n"));
        binds.push(bind);
    }
    let result_bind = binds.last().expect("non-empty chain");
    let body_rust = emit_map_body(map_body, map_param, result_bind)?;
    out.push_str(&format!("        let _updated = {body_rust};\n"));

    let mut value_bind = "_updated".to_string();
    for i in (1..chain.len()).rev() {
        let state_bind = &binds[i - 1];
        if is_focus_relative_put(graph, chain[i]) {
            let field = focus_put_field(graph, chain[i])?;
            out.push_str(&format!("        {state_bind}.{field} = {value_bind};\n"));
            value_bind = state_bind.clone();
        } else {
            let out_bind = format!("_p{i}");
            let expr = emit_leaf_put_value(graph, chain[i], state_bind, &value_bind)?;
            out.push_str(&format!("        let {out_bind} = {expr};\n"));
            emit_leaf_put_stores(graph, chain[i], "cursor_0", &out_bind, out)?;
            value_bind = out_bind;
        }
    }
    emit_leaf_put_stores(graph, chain[0], "cursor_0", &value_bind, out)?;
    out.push_str("    }\n}\n\n");
    Ok(())
}

fn fused_provenance_names(
    graph: &CgirGraph,
    original_ids: &[NodeId],
    fallback: &[String],
) -> String {
    let mut names = vec![];
    for &id in original_ids {
        if let Some(CgirNode::OpticLeaf { name, .. }) = graph.nodes.get(id as usize) {
            if !names.contains(name) {
                names.push(name.clone());
            }
        }
    }
    if names.is_empty() {
        fallback.join(", ")
    } else {
        names.join(", ")
    }
}

fn compose_primary_field(graph: &CgirGraph, entry_leaf: NodeId) -> Result<String, String> {
    let CgirNode::OpticLeaf { summary, .. } = graph
        .nodes
        .get(entry_leaf as usize)
        .ok_or_else(|| format!("compose entry leaf {entry_leaf} missing"))?
    else {
        return Err(format!("compose entry leaf {entry_leaf} not a leaf"));
    };
    let reg = summary
        .get_reads
        .first()
        .ok_or_else(|| "compose lhs has no read region".to_string())?;
    lookup_region_field(&graph.region_map, reg)
}

fn is_focus_relative_put(graph: &CgirGraph, leaf_id: NodeId) -> bool {
    let Some(CgirNode::OpticLeaf { summary, .. }) = graph.nodes.get(leaf_id as usize) else {
        return false;
    };
    summary
        .put_writes
        .iter()
        .any(|r| !graph.region_map.is_top_level_column(r))
}

fn focus_put_field(graph: &CgirGraph, leaf_id: NodeId) -> Result<String, String> {
    let CgirNode::OpticLeaf { summary, .. } = graph
        .nodes
        .get(leaf_id as usize)
        .ok_or_else(|| format!("leaf {leaf_id} missing"))?
    else {
        return Err(format!("node {leaf_id} not OpticLeaf"));
    };
    if summary.put_writes.is_empty() {
        return Err(format!("leaf {leaf_id} has no put_writes"));
    }
    let paths: Vec<String> = summary
        .put_writes
        .iter()
        .map(|reg| {
            let path = graph.region_map.nested_field_path(reg);
            if path.is_empty() {
                reg.clone()
            } else {
                path.join(".")
            }
        })
        .collect();
    if paths.iter().all(|p| p == &paths[0]) {
        Ok(paths[0].clone())
    } else {
        Err(format!(
            "leaf {leaf_id} put_writes disagree on nested assignment path: {paths:?}"
        ))
    }
}

fn emit_leaf_get(
    graph: &CgirGraph,
    id: NodeId,
    cursor: &str,
    focus_bind: Option<&str>,
) -> Result<String, String> {
    let leaf = graph
        .nodes
        .get(id as usize)
        .ok_or_else(|| format!("leaf {id} missing"))?;
    validate_leaf_params(leaf)?;
    let CgirNode::OpticLeaf {
        get_body,
        get_param,
        ..
    } = leaf
    else {
        return Err(format!("node {id} not OpticLeaf"));
    };
    let mut body = get_body.as_ref().clone();
    if let Some(bind) = focus_bind {
        body = substitute_hir_var(&body, get_param, bind);
    }
    emit_pure_hir_expr(&body, cursor)
}

fn emit_leaf_put_value(
    graph: &CgirGraph,
    id: NodeId,
    state_bind: &str,
    value_bind: &str,
) -> Result<String, String> {
    let leaf = graph
        .nodes
        .get(id as usize)
        .ok_or_else(|| format!("leaf {id} missing"))?;
    validate_leaf_params(leaf)?;
    let CgirNode::OpticLeaf {
        put_value_body,
        put_state_param,
        put_value_param,
        ..
    } = leaf
    else {
        return Err(format!("node {id} not OpticLeaf"));
    };
    let Some(body) = put_value_body else {
        return Ok(value_bind.to_string());
    };
    let state = put_state_param.as_deref().unwrap_or("x");
    let value = put_value_param.as_deref().unwrap_or("v");
    let subbed = substitute_hir_vars(body.as_ref(), &[(state, state_bind), (value, value_bind)]);
    emit_pure_hir_expr(&subbed, "_unused")
}

fn emit_leaf_put_stores(
    graph: &CgirGraph,
    id: NodeId,
    cursor: &str,
    value_bind: &str,
    out: &mut String,
) -> Result<(), String> {
    let CgirNode::OpticLeaf { summary, .. } = graph
        .nodes
        .get(id as usize)
        .ok_or_else(|| format!("leaf {id} missing"))?
    else {
        return Err(format!("node {id} not OpticLeaf"));
    };
    let regions: Vec<_> = if summary.put_writes.is_empty() {
        summary
            .get_reads
            .first()
            .map(|r| vec![r.clone()])
            .unwrap_or_default()
    } else {
        summary.put_writes.clone()
    };
    if regions.is_empty() {
        return Ok(());
    }
    let mut stores = 0usize;
    for reg in &regions {
        if !graph.region_map.is_top_level_column(reg) {
            continue;
        }
        let field = lookup_region_field(&graph.region_map, reg)?;
        validate_user_ident(&field, "region field")?;
        out.push_str(&format!(
            "        {cursor}.arena.{field}[{cursor}.id] = {value_bind};\n"
        ));
        stores += 1;
    }
    if stores == 0 {
        return Err(format!(
            "leaf put_writes {:?} produced no top-level arena stores",
            summary.put_writes
        ));
    }
    Ok(())
}

fn detect_query_mode(graph: &CgirGraph) -> Result<QueryMode, String> {
    let has_product = graph
        .nodes
        .iter()
        .any(|n| matches!(n, CgirNode::Product { .. } | CgirNode::ProductFlat { .. }));

    if graph.roots.is_empty() {
        return Err("CGIR graph has no query root".into());
    }

    for &root in &graph.roots {
        if let Some(node) = graph.nodes.get(root as usize) {
            return Ok(match node {
                CgirNode::FusedLoop { compose_body, .. } if compose_body.is_some() => {
                    QueryMode::FusedCompose { root }
                }
                CgirNode::QueryGet { .. } => QueryMode::Get { root },
                CgirNode::QuerySet { .. } => QueryMode::Set { root },
                CgirNode::QueryMap { optic_name, .. } => {
                    if let Some(&nid) = graph.resolved_optics.get(optic_name) {
                        if matches!(
                            graph.nodes.get(nid as usize),
                            Some(CgirNode::Compose { .. })
                        ) {
                            return Ok(QueryMode::MapCompose {
                                root,
                                compose_id: nid,
                            });
                        }
                    }
                    if has_product {
                        QueryMode::MapProduct { root }
                    } else {
                        QueryMode::MapDecay { root }
                    }
                }
                other => {
                    return Err(format!("unsupported CGIR root node for codegen: {other:?}"));
                }
            });
        }
    }
    Err(format!(
        "CGIR root {:?} is out of bounds (nodes={})",
        graph.roots,
        graph.nodes.len()
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use optic_cgir::{CgirGraph, CgirNode};
    use optic_hir::{ConcreteGrade, Determinism, OpticSummary, OwnershipDim, PathLift, Rational};
    use optic_syntax::{BinOp, Span};
    use std::collections::BTreeMap;
    use std::sync::Arc;

    fn assert_rust_golden(example: &str) {
        let stem = example.trim_end_matches(".opt");
        let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../examples")
            .join(example);
        let src = std::fs::read_to_string(&path).expect("read example");
        let prog = optic_syntax::parse(&src, optic_syntax::SourceId(1)).expect("parse");
        let hir = optic_hir::lower(prog).expect("lower");
        let typed = optic_typeck::check(hir).expect("typeck");
        let cg = optic_cgir::build(&typed).expect("cgir");
        let graph = optic_opt::optimize(cg).expect("optimize").graph;
        let emitted = emit(&graph, "optic_runtime").expect("emit");
        let fixture = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../fixtures/rust")
            .join(format!("{stem}.rs"));
        if std::env::var("OPTIC_UPDATE_GOLDEN").is_ok() {
            std::fs::write(&fixture, &emitted).expect("write rust golden");
        } else {
            let expected = std::fs::read_to_string(&fixture).expect("rust golden");
            assert_eq!(emitted, expected, "rust golden mismatch for {example}");
        }
    }

    #[test]
    fn golden_rust_health_get() {
        assert_rust_golden("health_get.opt");
    }

    #[test]
    fn golden_rust_health_set() {
        assert_rust_golden("health_set.opt");
    }

    #[test]
    fn golden_rust_health_position() {
        assert_rust_golden("health_position.opt");
    }

    #[test]
    fn golden_rust_health_decay() {
        assert_rust_golden("health_decay.opt");
    }

    #[test]
    fn golden_rust_compose_decay() {
        assert_rust_golden("compose_decay.opt");
    }

    #[test]
    fn golden_rust_compose_triple() {
        assert_rust_golden("compose_triple.opt");
    }

    #[test]
    fn golden_rust_nested_position() {
        assert_rust_golden("nested_position.opt");
    }

    #[test]
    fn golden_rust_nested_field_triple() {
        assert_rust_golden("nested_field_triple.opt");
    }

    fn mk_region_map(cols: &[(&str, &str)]) -> RegionMap {
        let mut map = RegionMap::default();
        for (name, ty) in cols {
            map.columns.insert(
                (*name).to_string(),
                optic_hir::ColumnInfo {
                    name: (*name).to_string(),
                    rust_ty: (*ty).to_string(),
                    element_ty: None,
                },
            );
        }
        map
    }

    fn mk_leaf(name: &str, regions: Vec<&str>) -> (CgirNode, Arc<OpticSummary>) {
        let get_body = if regions.is_empty() {
            HirExpr::Var("x".into(), Span::dummy())
        } else {
            HirExpr::CursorIndex {
                cursor: "cursor".into(),
                field: regions[0].to_string(),
                span: Span::dummy(),
            }
        };
        let sum = OpticSummary {
            name: Some(name.into()),
            costate: "Entities".into(),
            focus: "f32".into(),
            lift: PathLift::default(),
            get_reads: regions.iter().map(|s| s.to_string()).collect(),
            put_reads: vec![],
            put_writes: regions.iter().map(|s| s.to_string()).collect(),
            get_grade: ConcreteGrade {
                cache: 1,
                ownership: OwnershipDim {
                    share: Rational::one(),
                    read_only: false,
                    must_use: false,
                },
            },
            put_grade: ConcreteGrade {
                cache: 1,
                ownership: OwnershipDim {
                    share: Rational::one(),
                    read_only: false,
                    must_use: false,
                },
            },
            get_determinism: Determinism::Pure,
            put_determinism: Determinism::Pure,
            serializable: true,
            provenance: Span::dummy(),
        };
        let arc = Arc::new(sum);
        let node = CgirNode::OpticLeaf {
            id: 0,
            name: name.into(),
            costate: "E".into(),
            focus: "f".into(),
            grade: arc.get_grade.clone(),
            get_fn: "".into(),
            put_fn: "".into(),
            get_param: if regions.is_empty() {
                "x".into()
            } else {
                "s".into()
            },
            get_body: Arc::new(get_body),
            put_state_param: if regions.is_empty() {
                Some("x".into())
            } else {
                Some("s".into())
            },
            put_value_param: Some("v".into()),
            put_value_body: Some(Arc::new(HirExpr::Var("v".into(), Span::dummy()))),
            summary: Arc::clone(&arc),
            provenance: Span::dummy(),
        };
        (node, arc)
    }

    #[test]
    fn test_detect_query_get_mode() {
        let (leaf, _) = mk_leaf("HealthView", vec!["healths"]);
        let g = CgirGraph {
            nodes: vec![
                leaf,
                CgirNode::QueryGet {
                    id: 1,
                    optic_name: "HealthView".into(),
                    costate: "entities".into(),
                    cursor: "cur".into(),
                    provenance: Span::dummy(),
                },
            ],
            roots: vec![1],
            provenance_index: BTreeMap::new(),
            resolved_optics: [("HealthView".into(), 0)].into_iter().collect(),
            region_map: mk_region_map(&[("healths", "Vec<f32>")]),
        };
        match detect_query_mode(&g).expect("detect mode") {
            QueryMode::Get { root } => assert_eq!(root, 1),
            _ => panic!("expected Get mode"),
        }
    }

    #[test]
    fn test_detect_query_set_mode() {
        let (leaf, _) = mk_leaf("HealthView", vec!["healths"]);
        let g = CgirGraph {
            nodes: vec![
                leaf,
                CgirNode::QuerySet {
                    id: 1,
                    optic_name: "HealthView".into(),
                    costate: "entities".into(),
                    cursor: "cur".into(),
                    value_repr: "42.5".into(),
                    provenance: Span::dummy(),
                },
            ],
            roots: vec![1],
            provenance_index: BTreeMap::new(),
            resolved_optics: [("HealthView".into(), 0)].into_iter().collect(),
            region_map: mk_region_map(&[("healths", "Vec<f32>")]),
        };
        match detect_query_mode(&g).expect("detect mode") {
            QueryMode::Set { root } => assert_eq!(root, 1),
            _ => panic!("expected Set mode"),
        }
    }

    #[test]
    fn test_emit_map_body_from_hir() {
        let body = HirExpr::Bin {
            op: BinOp::Sub,
            left: Box::new(HirExpr::Var("h".into(), Span::dummy())),
            right: Box::new(HirExpr::LitFloat(10.0, Span::dummy())),
            span: Span::dummy(),
        };
        assert_eq!(
            emit_map_body(&body, "h", "_healths").expect("emit body"),
            "_healths - 10.0"
        );
        let s = emit(
            &CgirGraph {
                nodes: vec![
                    mk_leaf("H", vec!["healths"]).0,
                    CgirNode::QueryMap {
                        id: 1,
                        optic_name: "H".into(),
                        costate: "e".into(),
                        cursor: "c".into(),
                        map_param: "h".into(),
                        map_body: Arc::new(body),
                        provenance: Span::dummy(),
                    },
                ],
                roots: vec![1],
                provenance_index: BTreeMap::new(),
                resolved_optics: [("H".into(), 0)].into_iter().collect(),
                region_map: mk_region_map(&[("healths", "Vec<f32>")]),
            },
            "r",
        )
        .expect("emit");
        assert!(s.contains("_healths - 10.0") || s.contains("(_healths - 10.0)"));
    }

    #[test]
    fn test_emit_rejects_hostile_optic_keyword_name() {
        let (leaf, _) = mk_leaf("fn", vec!["healths"]);
        let body = HirExpr::Var("h".into(), Span::dummy());
        let g = CgirGraph {
            nodes: vec![
                leaf,
                CgirNode::QueryMap {
                    id: 1,
                    optic_name: "fn".into(),
                    costate: "e".into(),
                    cursor: "c".into(),
                    map_param: "h".into(),
                    map_body: std::sync::Arc::new(body),
                    provenance: Span::dummy(),
                },
            ],
            roots: vec![1],
            provenance_index: BTreeMap::new(),
            resolved_optics: [("fn".into(), 0)].into_iter().collect(),
            region_map: mk_region_map(&[("healths", "Vec<f32>")]),
        };
        let err = emit(&g, "optic_runtime").expect_err("keyword optic name must fail emit");
        assert!(
            err.contains("reserved Rust keyword") || err.contains("invalid Rust identifier"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn test_is_valid_rust_ident_rejects_invalid() {
        assert!(is_valid_rust_ident("HealthView"));
        assert!(is_valid_rust_ident("_h"));
        assert!(!is_valid_rust_ident(""));
        assert!(!is_valid_rust_ident("9bad"));
        assert!(!is_valid_rust_ident("bad-name"));
        assert!(!is_valid_rust_ident("fn"));
        assert!(!is_valid_rust_ident("match"));
    }

    #[test]
    fn test_emit_health_get_matches_fixture_shape() {
        let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../examples/health_get.opt");
        let src = std::fs::read_to_string(&path).expect("read health_get.opt");
        let prog = optic_syntax::parse(&src, optic_syntax::SourceId(1)).expect("parse");
        let hir = optic_hir::lower(prog).expect("lower");
        let typed = optic_typeck::check(hir).expect("typeck");
        let cg = optic_cgir::build(&typed).expect("cgir");
        let graph = optic_opt::optimize(cg).expect("optimize").graph;
        let emitted = emit(&graph, "optic_runtime").expect("emit");
        let fixture = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../fixtures/rust/health_get.rs");
        let expected = std::fs::read_to_string(&fixture).expect("fixture rust");
        for needle in [
            "println!(\"get: {}\", _v);",
            "cursor_0.arena.healths",
            "pub positions:",
        ] {
            assert!(emitted.contains(needle), "missing {needle}");
            assert!(expected.contains(needle), "fixture missing {needle}");
        }
    }

    #[test]
    fn test_emit_health_set_matches_fixture_shape() {
        let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../examples/health_set.opt");
        let src = std::fs::read_to_string(&path).expect("read health_set.opt");
        let prog = optic_syntax::parse(&src, optic_syntax::SourceId(1)).expect("parse");
        let hir = optic_hir::lower(prog).expect("lower");
        let typed = optic_typeck::check(hir).expect("typeck");
        let cg = optic_cgir::build(&typed).expect("cgir");
        let graph = optic_opt::optimize(cg).expect("optimize").graph;
        let emitted = emit(&graph, "optic_runtime").expect("emit");
        let fixture = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../fixtures/rust/health_set.rs");
        let expected = std::fs::read_to_string(&fixture).expect("fixture rust");
        for needle in [
            "cursor_0.arena.healths[cursor_0.id] = 42.0;",
            "pub fn run_example",
        ] {
            assert!(emitted.contains(needle), "missing {needle}");
            assert!(expected.contains(needle), "fixture missing {needle}");
        }
    }

    #[test]
    fn test_emit_health_position_matches_fixture_shape() {
        let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../examples/health_position.opt");
        let src = std::fs::read_to_string(&path).expect("read health_position.opt");
        let prog = optic_syntax::parse(&src, optic_syntax::SourceId(1)).expect("parse");
        let hir = optic_hir::lower(prog).expect("lower");
        let typed = optic_typeck::check(hir).expect("typeck");
        let cg = optic_cgir::build(&typed).expect("cgir");
        let graph = optic_opt::optimize(cg).expect("optimize").graph;
        let emitted = emit(&graph, "optic_runtime").expect("emit");
        let fixture = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../fixtures/rust/health_position.rs");
        let expected = std::fs::read_to_string(&fixture).expect("fixture rust");
        for needle in [
            "let _healths = cursor_0.arena.healths[cursor_0.id];",
            "let _positions = cursor_0.arena.positions[cursor_0.id];",
            "_healths - 1.0",
            "_positions.0 + 0.1",
            "cursor_0.arena.healths[cursor_0.id] = _healths_new;",
            "cursor_0.arena.positions[cursor_0.id] = _positions_new;",
        ] {
            assert!(emitted.contains(needle), "missing {needle}");
            assert!(expected.contains(needle), "fixture missing {needle}");
        }
    }

    #[test]
    fn test_emit_health_decay_matches_fixture_shape() {
        let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../examples/health_decay.opt");
        let src = std::fs::read_to_string(&path).expect("read health_decay.opt");
        let prog = optic_syntax::parse(&src, optic_syntax::SourceId(1)).expect("parse");
        let hir = optic_hir::lower(prog).expect("lower");
        let typed = optic_typeck::check(hir).expect("typeck");
        let cg = optic_cgir::build(&typed).expect("cgir");
        let graph = optic_opt::optimize(cg).expect("optimize").graph;
        let emitted = emit(&graph, "optic_runtime").expect("emit");
        let fixture = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../fixtures/rust/health_decay.rs");
        let expected = std::fs::read_to_string(&fixture).expect("fixture rust");
        for needle in [
            "let _healths = cursor_0.arena.healths[cursor_0.id];",
            "_healths - 10.0",
            "cursor_0.arena.healths[cursor_0.id] =",
        ] {
            assert!(emitted.contains(needle), "missing {needle}");
            assert!(expected.contains(needle), "fixture missing {needle}");
        }
    }

    #[test]
    fn test_nested_position_compose_fusion_execution_equivalence() {
        let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../examples/nested_position.opt");
        let src = std::fs::read_to_string(&path).expect("read nested_position.opt");
        let prog = optic_syntax::parse(&src, optic_syntax::SourceId(1)).expect("parse");
        let hir = optic_hir::lower(prog).expect("lower");
        let typed = optic_typeck::check(hir).expect("typeck");
        let cg = optic_cgir::build(&typed).expect("cgir");
        let pre = optic_opt::optimize_without_compose_fusion(cg.clone()).expect("pre-opt");
        let post = optic_opt::optimize(cg).expect("post-opt");
        let pre_rs = emit(&pre, "optic_runtime").expect("pre emit");
        let post_rs = emit(&post.graph, "optic_runtime").expect("post emit");
        let pre_after = run_emitted_and_capture_after(&pre_rs);
        let post_after = run_emitted_and_capture_after(&post_rs);
        assert_eq!(
            pre_after, post_after,
            "nested_position fusion must preserve output"
        );
        assert!(
            pre_after.contains("0.1") && pre_after.contains("1.1") && pre_after.contains("2.1"),
            "unexpected nested position mutations: {pre_after}"
        );
    }

    #[test]
    fn test_compose_fusion_execution_equivalence() {
        let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../examples/compose_decay.opt");
        let src = std::fs::read_to_string(&path).expect("read compose_decay.opt");
        let prog = optic_syntax::parse(&src, optic_syntax::SourceId(1)).expect("parse");
        let hir = optic_hir::lower(prog).expect("lower");
        let typed = optic_typeck::check(hir).expect("typeck");
        let cg = optic_cgir::build(&typed).expect("cgir");
        let pre = optic_opt::optimize_without_compose_fusion(cg.clone()).expect("pre-opt");
        let post = optic_opt::optimize(cg).expect("post-opt");
        assert!(
            post.graph
                .roots
                .first()
                .and_then(|&r| post.graph.nodes.get(r as usize))
                .is_some_and(|n| matches!(
                    n,
                    CgirNode::FusedLoop {
                        compose_body: Some(_),
                        ..
                    }
                )),
            "post-fusion root must be FusedLoop with compose_body"
        );
        let pre_rs = emit(&pre, "optic_runtime").expect("pre emit");
        let post_rs = emit(&post.graph, "optic_runtime").expect("post emit");
        assert!(
            pre_rs.contains("let _c0 =") && pre_rs.contains("let _c1 ="),
            "unfused compose must use chain temps"
        );
        assert!(
            post_rs.contains("optic(fused):"),
            "fused compose must carry provenance comment"
        );
        let pre_after = run_emitted_and_capture_after(&pre_rs);
        let post_after = run_emitted_and_capture_after(&post_rs);
        assert_eq!(
            pre_after, post_after,
            "compose fusion must preserve mutations (pre={pre_after}, post={post_after})"
        );
        assert!(
            pre_after.contains("95.0") && pre_after.contains("75.0") && pre_after.contains("45.0"),
            "unexpected mutations: {pre_after}"
        );
    }

    fn run_emitted_and_capture_after(emitted: &str) -> String {
        let tmp = tempfile::tempdir().expect("tempdir");
        let runtime = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../optic-runtime");
        std::fs::write(
            tmp.path().join("Cargo.toml"),
            format!(
                "[package]\nname=\"v\"\nversion=\"0.1.0\"\nedition=\"2021\"\n[dependencies]\noptic-runtime = {{ path = \"{}\" }}\n[[bin]]\nname=\"v\"\npath=\"main.rs\"\n",
                runtime.display()
            ),
        )
        .expect("manifest");
        std::fs::write(tmp.path().join("main.rs"), emitted).expect("main.rs");
        let out = std::process::Command::new("cargo")
            .args([
                "run",
                "--quiet",
                "--manifest-path",
                &tmp.path().join("Cargo.toml").to_string_lossy(),
            ])
            .current_dir(tmp.path())
            .output()
            .expect("cargo run");
        assert!(
            out.status.success(),
            "run failed: {}",
            String::from_utf8_lossy(&out.stderr)
        );
        let stdout = String::from_utf8_lossy(&out.stdout);
        stdout
            .lines()
            .find(|l| l.starts_with("after:"))
            .unwrap_or_else(|| panic!("missing after line in {stdout}"))
            .to_string()
    }

    #[test]
    fn test_emit_rejects_hostile_map_param_keyword() {
        let (leaf, _) = mk_leaf("H", vec!["healths"]);
        let body = HirExpr::Var("h".into(), Span::dummy());
        let g = CgirGraph {
            nodes: vec![
                leaf,
                CgirNode::QueryMap {
                    id: 1,
                    optic_name: "H".into(),
                    costate: "e".into(),
                    cursor: "c".into(),
                    map_param: "fn".into(),
                    map_body: std::sync::Arc::new(body),
                    provenance: Span::dummy(),
                },
            ],
            roots: vec![1],
            provenance_index: BTreeMap::new(),
            resolved_optics: [("H".into(), 0)].into_iter().collect(),
            region_map: mk_region_map(&[("healths", "Vec<f32>")]),
        };
        let err = emit(&g, "optic_runtime").expect_err("keyword map param");
        assert!(err.contains("reserved Rust keyword") || err.contains("invalid Rust identifier"));
    }

    #[test]
    fn test_emit_rejects_hostile_region_field_keyword() {
        let (mut leaf, _) = mk_leaf("H", vec!["type"]);
        if let CgirNode::OpticLeaf { summary, .. } = &mut leaf {
            let mut sum = (**summary).clone();
            sum.get_reads = vec!["type".into()];
            sum.put_writes = vec!["type".into()];
            *summary = Arc::new(sum);
        }
        let body = HirExpr::Var("h".into(), Span::dummy());
        let g = CgirGraph {
            nodes: vec![
                leaf,
                CgirNode::QueryMap {
                    id: 1,
                    optic_name: "H".into(),
                    costate: "e".into(),
                    cursor: "c".into(),
                    map_param: "h".into(),
                    map_body: std::sync::Arc::new(body),
                    provenance: Span::dummy(),
                },
            ],
            roots: vec![1],
            provenance_index: BTreeMap::new(),
            resolved_optics: [("H".into(), 0)].into_iter().collect(),
            region_map: mk_region_map(&[("type", "Vec<f32>")]),
        };
        let err = emit(&g, "optic_runtime").expect_err("keyword region field");
        assert!(err.contains("region field"));
    }

    #[test]
    fn detect_query_mode_errors_without_root() {
        let g = CgirGraph {
            nodes: vec![],
            roots: vec![],
            provenance_index: BTreeMap::new(),
            resolved_optics: Default::default(),
            region_map: RegionMap::default(),
        };
        assert!(detect_query_mode(&g).is_err());
    }

    #[test]
    fn emit_leaf_put_value_substitutes_structurally() {
        let body = HirExpr::Bin {
            op: BinOp::Div,
            left: Box::new(HirExpr::Var("v".into(), Span::dummy())),
            right: Box::new(HirExpr::Var("x".into(), Span::dummy())),
            span: Span::dummy(),
        };
        let (mut leaf, _) = mk_leaf("D", vec![]);
        if let CgirNode::OpticLeaf {
            put_value_body,
            put_state_param,
            ..
        } = &mut leaf
        {
            *put_state_param = Some("x".into());
            *put_value_body = Some(Arc::new(body));
        }
        let g = CgirGraph {
            nodes: vec![leaf],
            roots: vec![],
            provenance_index: BTreeMap::new(),
            resolved_optics: Default::default(),
            region_map: RegionMap::default(),
        };
        let rust = emit_leaf_put_value(&g, 0, "_intermediate", "_updated").expect("put value");
        assert_eq!(rust, "_updated / _intermediate");
    }

    #[test]
    fn test_emit_rejects_hostile_compose_get_param() {
        let (mut h_leaf, _) = mk_leaf("H", vec!["healths"]);
        if let CgirNode::OpticLeaf { get_param, .. } = &mut h_leaf {
            *get_param = "fn".into();
        }
        let (d_leaf, _) = mk_leaf("D", vec![]);
        let body = HirExpr::Var("y".into(), Span::dummy());
        let g = CgirGraph {
            nodes: vec![
                h_leaf,
                d_leaf,
                CgirNode::Compose {
                    id: 2,
                    lhs: 0,
                    rhs: 1,
                    grade: ConcreteGrade {
                        cache: 1,
                        ownership: OwnershipDim {
                            share: Rational::one(),
                            read_only: false,
                            must_use: false,
                        },
                    },
                    provenance: Span::dummy(),
                },
                CgirNode::QueryMap {
                    id: 3,
                    optic_name: "pipe".into(),
                    costate: "entities".into(),
                    cursor: "c".into(),
                    map_param: "y".into(),
                    map_body: Arc::new(body),
                    provenance: Span::dummy(),
                },
            ],
            roots: vec![3],
            provenance_index: BTreeMap::new(),
            resolved_optics: [("pipe".into(), 2)].into_iter().collect(),
            region_map: mk_region_map(&[("healths", "Vec<f32>")]),
        };
        let err = emit(&g, "optic_runtime").expect_err("keyword get_param in compose");
        assert!(err.contains("get parameter") || err.contains("keyword"));
    }

    #[test]
    fn test_emit_rejects_invalid_set_value_repr() {
        let (leaf, _) = mk_leaf("H", vec!["healths"]);
        let g = CgirGraph {
            nodes: vec![
                leaf,
                CgirNode::QuerySet {
                    id: 1,
                    optic_name: "H".into(),
                    costate: "entities".into(),
                    cursor: "c".into(),
                    value_repr: "not_a_number();".into(),
                    provenance: Span::dummy(),
                },
            ],
            roots: vec![1],
            provenance_index: BTreeMap::new(),
            resolved_optics: [("H".into(), 0)].into_iter().collect(),
            region_map: mk_region_map(&[("healths", "Vec<f32>")]),
        };
        let err = emit(&g, "optic_runtime").expect_err("invalid set literal");
        assert!(err.contains("f32 literal"));
    }

    #[test]
    fn test_emit_compose_triple_matches_fixture_shape() {
        let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../examples/compose_triple.opt");
        let src = std::fs::read_to_string(&path).expect("read compose_triple.opt");
        let prog = optic_syntax::parse(&src, optic_syntax::SourceId(1)).expect("parse");
        let hir = optic_hir::lower(prog).expect("lower");
        let typed = optic_typeck::check(hir).expect("typeck");
        let cg = optic_cgir::build(&typed).expect("cgir");
        let graph = optic_opt::optimize(cg).expect("optimize").graph;
        let emitted = emit(&graph, "optic_runtime").expect("emit");
        let fixture = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../fixtures/rust/compose_triple.rs");
        let expected = std::fs::read_to_string(&fixture).expect("fixture rust");
        for needle in [
            "optic(fused): [HealthView, DoubleView, TripleView]",
            "let _c0 = cursor_0.arena.healths[cursor_0.id];",
            "_c0 * 2.0",
            "_c1 * 3.0",
            "_updated / 3.0",
            "_p2 / 2.0",
        ] {
            assert!(emitted.contains(needle), "missing {needle}");
            assert!(expected.contains(needle), "fixture missing {needle}");
        }
    }

    #[test]
    fn test_emit_compose_decay_matches_fixture_shape() {
        let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../examples/compose_decay.opt");
        let src = std::fs::read_to_string(&path).expect("read compose_decay.opt");
        let prog = optic_syntax::parse(&src, optic_syntax::SourceId(1)).expect("parse");
        let hir = optic_hir::lower(prog).expect("lower");
        let typed = optic_typeck::check(hir).expect("typeck");
        let cg = optic_cgir::build(&typed).expect("cgir");
        let graph = optic_opt::optimize(cg).expect("optimize").graph;
        let emitted = emit(&graph, "optic_runtime").expect("emit");
        let fixture = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../fixtures/rust/compose_decay.rs");
        let expected = std::fs::read_to_string(&fixture).expect("fixture rust");
        for needle in [
            "optic(fused):",
            "let _c0 = cursor_0.arena.healths[cursor_0.id];",
            "_c0 * 2.0",
            "_updated / 2.0",
            "cursor_0.arena.healths[cursor_0.id] = _p1;",
        ] {
            assert!(emitted.contains(needle), "missing {needle}");
            assert!(expected.contains(needle), "fixture missing {needle}");
        }
    }

    #[test]
    fn emit_compose_emits_rhs_put_writes() {
        let (h_leaf, _) = mk_leaf("H", vec!["healths"]);
        let (mut p_leaf, _) = mk_leaf("P", vec!["positions"]);
        if let CgirNode::OpticLeaf { summary, .. } = &mut p_leaf {
            let mut sum = (**summary).clone();
            sum.costate = "f32".into();
            sum.focus = "f32".into();
            sum.get_reads = vec!["positions".into()];
            sum.put_writes = vec!["positions".into()];
            *summary = Arc::new(sum);
        }
        let body = HirExpr::Var("y".into(), Span::dummy());
        let g = CgirGraph {
            nodes: vec![
                h_leaf,
                p_leaf,
                CgirNode::Compose {
                    id: 2,
                    lhs: 0,
                    rhs: 1,
                    grade: ConcreteGrade {
                        cache: 1,
                        ownership: OwnershipDim {
                            share: Rational::one(),
                            read_only: false,
                            must_use: false,
                        },
                    },
                    provenance: Span::dummy(),
                },
                CgirNode::QueryMap {
                    id: 3,
                    optic_name: "pipe".into(),
                    costate: "entities".into(),
                    cursor: "c".into(),
                    map_param: "y".into(),
                    map_body: Arc::new(body),
                    provenance: Span::dummy(),
                },
            ],
            roots: vec![3],
            provenance_index: BTreeMap::new(),
            resolved_optics: [("pipe".into(), 2)].into_iter().collect(),
            region_map: mk_region_map(&[("healths", "Vec<f32>"), ("positions", "Vec<(f32, f32)>")]),
        };
        let emitted = emit(&g, "optic_runtime").expect("emit compose with rhs put_writes");
        assert!(emitted.contains("cursor_0.arena.positions[cursor_0.id] = _p1;"));
        assert!(emitted.contains("cursor_0.arena.healths[cursor_0.id] = _p1;"));
    }

    #[test]
    fn test_emit_rejects_hostile_fused_compose_get_param() {
        let (mut h_leaf, _) = mk_leaf("H", vec!["healths"]);
        if let CgirNode::OpticLeaf { get_param, .. } = &mut h_leaf {
            *get_param = "type".into();
        }
        let (d_leaf, _) = mk_leaf("D", vec![]);
        let map_body = Arc::new(HirExpr::Var("y".into(), Span::dummy()));
        let g = CgirGraph {
            nodes: vec![
                h_leaf,
                d_leaf,
                CgirNode::Compose {
                    id: 2,
                    lhs: 0,
                    rhs: 1,
                    grade: ConcreteGrade {
                        cache: 1,
                        ownership: OwnershipDim {
                            share: Rational::one(),
                            read_only: false,
                            must_use: false,
                        },
                    },
                    provenance: Span::dummy(),
                },
                CgirNode::FusedLoop {
                    id: 3,
                    original_ids: vec![0, 1, 2],
                    costate: "entities".into(),
                    provenance: Span::dummy(),
                    compose_body: Some(optic_cgir::ComposeFusedBody {
                        compose_id: 2,
                        lhs: 0,
                        rhs: 1,
                        map_param: "y".into(),
                        map_body: map_body.clone(),
                    }),
                },
            ],
            roots: vec![3],
            provenance_index: BTreeMap::new(),
            resolved_optics: Default::default(),
            region_map: mk_region_map(&[("healths", "Vec<f32>")]),
        };
        let err = emit(&g, "optic_runtime").expect_err("keyword get_param in fused compose");
        assert!(
            err.contains("get parameter")
                || err.contains("keyword")
                || err.contains("reserved Rust"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn test_emit_product_map_tuple_body() {
        let (h_leaf, _) = mk_leaf("HealthView", vec!["healths"]);
        let (p_leaf, _) = mk_leaf("PositionView", vec!["positions"]);
        let body = HirExpr::Tuple(
            vec![
                HirExpr::Bin {
                    op: BinOp::Sub,
                    left: Box::new(HirExpr::Var("h".into(), Span::dummy())),
                    right: Box::new(HirExpr::LitFloat(1.0, Span::dummy())),
                    span: Span::dummy(),
                },
                HirExpr::Tuple(
                    vec![
                        HirExpr::TupleProj {
                            base: Box::new(HirExpr::Var("p".into(), Span::dummy())),
                            index: 0,
                            span: Span::dummy(),
                        },
                        HirExpr::Var("p".into(), Span::dummy()),
                    ],
                    Span::dummy(),
                ),
            ],
            Span::dummy(),
        );
        let g = CgirGraph {
            nodes: vec![
                h_leaf,
                p_leaf,
                CgirNode::Product {
                    id: 2,
                    lhs: 0,
                    rhs: 1,
                    grade: ConcreteGrade {
                        cache: 2,
                        ownership: OwnershipDim {
                            share: Rational::one(),
                            read_only: false,
                            must_use: false,
                        },
                    },
                    alias_safe: true,
                    provenance: Span::dummy(),
                },
                CgirNode::QueryMap {
                    id: 3,
                    optic_name: "combined".into(),
                    costate: "entities".into(),
                    cursor: "c".into(),
                    map_param: "h,p".into(),
                    map_body: Arc::new(body),
                    provenance: Span::dummy(),
                },
            ],
            roots: vec![3],
            provenance_index: BTreeMap::new(),
            resolved_optics: [("combined".into(), 2)].into_iter().collect(),
            region_map: mk_region_map(&[("healths", "Vec<f32>"), ("positions", "Vec<(f32, f32)>")]),
        };
        let s = emit(&g, "r").expect("emit product map");
        assert!(s.contains("_healths - 1.0"));
        assert!(s.contains("_positions.0"));
        assert!(s.contains("positions"));
    }

    #[test]
    fn test_emit_rejects_empty_region_map_columns() {
        let (leaf, _) = mk_leaf("H", vec!["healths"]);
        let g = CgirGraph {
            nodes: vec![
                leaf,
                CgirNode::QueryGet {
                    id: 1,
                    optic_name: "H".into(),
                    costate: "entities".into(),
                    cursor: "cur".into(),
                    provenance: Span::dummy(),
                },
            ],
            roots: vec![1],
            provenance_index: BTreeMap::new(),
            resolved_optics: [("H".into(), 0)].into_iter().collect(),
            region_map: RegionMap::default(),
        };
        let err = emit(&g, "optic_runtime").expect_err("empty columns");
        assert!(err.contains("no columns"));
    }

    #[test]
    fn test_emit_rejects_unknown_region_field() {
        let (leaf, _) = mk_leaf("H", vec!["ghosts"]);
        let g = CgirGraph {
            nodes: vec![
                leaf,
                CgirNode::QueryGet {
                    id: 1,
                    optic_name: "H".into(),
                    costate: "entities".into(),
                    cursor: "cur".into(),
                    provenance: Span::dummy(),
                },
            ],
            roots: vec![1],
            provenance_index: BTreeMap::new(),
            resolved_optics: [("H".into(), 0)].into_iter().collect(),
            region_map: mk_region_map(&[("healths", "Vec<f32>")]),
        };
        let err = emit(&g, "optic_runtime").expect_err("unknown region");
        assert!(err.contains("ghosts") || err.contains("unknown") || err.contains("region"));
    }

    #[test]
    fn test_emit_rejects_put_writes_without_top_level_stores() {
        let (entry, _) = mk_leaf("Entry", vec!["transforms"]);
        let (mut exit, _) = mk_leaf("Exit", vec![]);
        if let CgirNode::OpticLeaf { summary, .. } = &mut exit {
            let mut sum = (**summary).clone();
            sum.costate = "Transform".into();
            sum.focus = "f32".into();
            sum.put_writes = vec![];
            sum.get_reads = vec!["orphan_col".into()];
            *summary = Arc::new(sum);
        }
        let body = HirExpr::Var("v".into(), Span::dummy());
        let g = CgirGraph {
            nodes: vec![
                entry,
                exit,
                CgirNode::Compose {
                    id: 2,
                    lhs: 0,
                    rhs: 1,
                    grade: ConcreteGrade {
                        cache: 1,
                        ownership: OwnershipDim {
                            share: Rational::one(),
                            read_only: false,
                            must_use: false,
                        },
                    },
                    provenance: Span::dummy(),
                },
                CgirNode::QueryMap {
                    id: 3,
                    optic_name: "pipe".into(),
                    costate: "entities".into(),
                    cursor: "c".into(),
                    map_param: "v".into(),
                    map_body: Arc::new(body),
                    provenance: Span::dummy(),
                },
            ],
            roots: vec![3],
            provenance_index: BTreeMap::new(),
            resolved_optics: [("pipe".into(), 2)].into_iter().collect(),
            region_map: mk_region_map(&[("transforms", "Vec<Transform>")]),
        };
        let err = emit(&g, "optic_runtime").expect_err("non-top-level put_writes");
        assert!(
            err.contains("no top-level arena stores"),
            "unexpected emit error: {err}"
        );
    }

    #[test]
    fn test_nested_field_triple_compose_fusion_execution_equivalence() {
        let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../examples/nested_field_triple.opt");
        let src = std::fs::read_to_string(&path).expect("read nested_field_triple.opt");
        let prog = optic_syntax::parse(&src, optic_syntax::SourceId(1)).expect("parse");
        let hir = optic_hir::lower(prog).expect("lower");
        let typed = optic_typeck::check(hir).expect("typeck");
        let cg = optic_cgir::build(&typed).expect("cgir");
        let pre = optic_opt::optimize_without_compose_fusion(cg.clone()).expect("pre-opt");
        let post = optic_opt::optimize(cg).expect("post-opt");
        let pre_rs = emit(&pre, "optic_runtime").expect("pre emit");
        let post_rs = emit(&post.graph, "optic_runtime").expect("post emit");
        let pre_after = run_emitted_and_capture_after(&pre_rs);
        let post_after = run_emitted_and_capture_after(&post_rs);
        assert_eq!(
            pre_after, post_after,
            "nested_field_triple fusion must preserve output"
        );
        assert!(
            pre_after.contains("tag: 0.1"),
            "unexpected nested_field_triple mutations: {pre_after}"
        );
    }

    #[test]
    fn test_focus_put_field_rejects_disagreeing_paths() {
        let (mut leaf, _) = mk_leaf("BadPut", vec!["transforms"]);
        if let CgirNode::OpticLeaf { summary, .. } = &mut leaf {
            let mut sum = (**summary).clone();
            sum.put_writes = vec!["transforms.position".into(), "transforms.meta".into()];
            *summary = Arc::new(sum);
        }
        let g = CgirGraph {
            nodes: vec![leaf],
            roots: vec![],
            provenance_index: BTreeMap::new(),
            resolved_optics: Default::default(),
            region_map: mk_region_map(&[("transforms", "Vec<Transform>")]),
        };
        let err = focus_put_field(&g, 0).expect_err("disagreeing put paths");
        assert!(err.contains("disagree on nested assignment path"));
    }

    #[test]
    fn test_emit_nested_position_matches_fixture_shape() {
        let path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../examples/nested_position.opt");
        let src = std::fs::read_to_string(&path).expect("read nested_position.opt");
        let prog = optic_syntax::parse(&src, optic_syntax::SourceId(1)).expect("parse");
        let hir = optic_hir::lower(prog).expect("lower");
        let typed = optic_typeck::check(hir).expect("typeck");
        let cg = optic_cgir::build(&typed).expect("cgir");
        let graph = optic_opt::optimize(cg).expect("optimize").graph;
        let emitted = emit(&graph, "optic_runtime").expect("emit");
        let fixture = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../fixtures/rust/nested_position.rs");
        let expected = std::fs::read_to_string(&fixture).expect("fixture rust");
        for needle in [
            "optic(fused): [TransformView, PositionField]",
            "let mut _c0 = cursor_0.arena.transforms[cursor_0.id];",
            "let _c1 = _c0.position;",
            "_c0.position = _updated;",
            "cursor_0.arena.transforms[cursor_0.id] = _c0;",
        ] {
            assert!(emitted.contains(needle), "missing {needle}");
            assert!(expected.contains(needle), "fixture missing {needle}");
        }
    }
}
